/*******************************************************************************
 * Copyright (c) 2013, SAP AG
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions 
 * are met:
 *  
 *     - Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *     - Redistributions in binary form must reproduce the above copyright 
 *      notice, this list of conditions and the following disclaimer in the 
 *      documentation and/or other materials provided with the distribution.
 *     - Neither the name of the SAP AG nor the names of its contributors may
 *      be used to endorse or promote products derived from this software 
 *      without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF 
 * THE POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.03 at 09:58:45 AM CET 
//


package eu.primelife.ppl.policy.xacml.impl;

import java.io.Serializable;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.namespace.QName;
import org.jvnet.hyperjaxb3.item.Item;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XmlAdapterUtils;

@XmlAccessorType(XmlAccessType.FIELD)
@Entity(name = "eu.primelife.ppl.policy.xacml.impl.PolicySetTypePolicySetOrPolicyOrPolicySetIdReferenceItem")
@Table(name = "POLICYSETTYPEPOLICYSETORPOLI_0")
@Inheritance(strategy = InheritanceType.JOINED)
public class PolicySetTypePolicySetOrPolicyOrPolicySetIdReferenceItem
    implements Serializable, Item<JAXBElement<?>>
{

    @XmlElementRefs({
        @XmlElementRef(name = "PolicyCombinerParameters", namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", type = JAXBElement.class),
        @XmlElementRef(name = "PolicyIdReference", namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", type = JAXBElement.class),
        @XmlElementRef(name = "Policy", namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", type = JAXBElement.class),
        @XmlElementRef(name = "PolicySetCombinerParameters", namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", type = JAXBElement.class),
        @XmlElementRef(name = "PolicySetIdReference", namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", type = JAXBElement.class),
        @XmlElementRef(name = "CombinerParameters", namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", type = JAXBElement.class),
        @XmlElementRef(name = "PolicySet", namespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", type = JAXBElement.class)
    })
    protected JAXBElement<?> item;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * 
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PolicyCombinerParametersType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IdReferenceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link eu.primelife.ppl.policy.xacml.impl.PolicyType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PolicySetCombinerParametersType }{@code >}
     *     {@link JAXBElement }{@code <}{@link eu.primelife.ppl.policy.impl.PolicyType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IdReferenceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CombinerParametersType }{@code >}
     *     {@link JAXBElement }{@code <}{@link eu.primelife.ppl.policy.impl.PolicySetType }{@code >}
     *     {@link JAXBElement }{@code <}{@link eu.primelife.ppl.policy.xacml.impl.PolicySetType }{@code >}
     *     
     */
    @Transient
    public JAXBElement<?> getItem() {
        return item;
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PolicyCombinerParametersType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IdReferenceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link eu.primelife.ppl.policy.xacml.impl.PolicyType }{@code >}
     *     {@link JAXBElement }{@code <}{@link PolicySetCombinerParametersType }{@code >}
     *     {@link JAXBElement }{@code <}{@link eu.primelife.ppl.policy.impl.PolicyType }{@code >}
     *     {@link JAXBElement }{@code <}{@link IdReferenceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link CombinerParametersType }{@code >}
     *     {@link JAXBElement }{@code <}{@link eu.primelife.ppl.policy.impl.PolicySetType }{@code >}
     *     {@link JAXBElement }{@code <}{@link eu.primelife.ppl.policy.xacml.impl.PolicySetType }{@code >}
     *     
     */
    public void setItem(JAXBElement<?> value) {
        this.item = ((JAXBElement<?> ) value);
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    @SuppressWarnings("unchecked")
    @ManyToOne(targetEntity = PolicyCombinerParametersType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ITEMPOLICYCOMBINERPARAMETERS_0")
    public PolicyCombinerParametersType getItemPolicyCombinerParameters() {
        if (XmlAdapterUtils.isJAXBElement(PolicyCombinerParametersType.class, new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "PolicyCombinerParameters"), JAXBElement.GlobalScope.class, this.getItem())) {
            return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends PolicyCombinerParametersType> ) this.getItem()));
        } else {
            return null;
        }
    }

    public void setItemPolicyCombinerParameters(PolicyCombinerParametersType target) {
        if (target!= null) {
            setItem(XmlAdapterUtils.marshallJAXBElement(PolicyCombinerParametersType.class, new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "PolicyCombinerParameters"), JAXBElement.GlobalScope.class, target));
        }
    }

    @SuppressWarnings("unchecked")
    @ManyToOne(targetEntity = IdReferenceType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ITEMPOLICYIDREFERENCE_POLICY_0")
    public IdReferenceType getItemPolicyIdReference() {
        if (XmlAdapterUtils.isJAXBElement(IdReferenceType.class, new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "PolicyIdReference"), JAXBElement.GlobalScope.class, this.getItem())) {
            return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends IdReferenceType> ) this.getItem()));
        } else {
            return null;
        }
    }

    public void setItemPolicyIdReference(IdReferenceType target) {
        if (target!= null) {
            setItem(XmlAdapterUtils.marshallJAXBElement(IdReferenceType.class, new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "PolicyIdReference"), JAXBElement.GlobalScope.class, target));
        }
    }

    @SuppressWarnings("unchecked")
    @ManyToOne(targetEntity = PolicySetCombinerParametersType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ITEMPOLICYSETCOMBINERPARAMET_1")
    public PolicySetCombinerParametersType getItemPolicySetCombinerParameters() {
        if (XmlAdapterUtils.isJAXBElement(PolicySetCombinerParametersType.class, new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "PolicySetCombinerParameters"), JAXBElement.GlobalScope.class, this.getItem())) {
            return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends PolicySetCombinerParametersType> ) this.getItem()));
        } else {
            return null;
        }
    }

    public void setItemPolicySetCombinerParameters(PolicySetCombinerParametersType target) {
        if (target!= null) {
            setItem(XmlAdapterUtils.marshallJAXBElement(PolicySetCombinerParametersType.class, new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "PolicySetCombinerParameters"), JAXBElement.GlobalScope.class, target));
        }
    }

    @SuppressWarnings("unchecked")
    @ManyToOne(targetEntity = IdReferenceType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ITEMPOLICYSETIDREFERENCE_POL_0")
    public IdReferenceType getItemPolicySetIdReference() {
        if (XmlAdapterUtils.isJAXBElement(IdReferenceType.class, new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "PolicySetIdReference"), JAXBElement.GlobalScope.class, this.getItem())) {
            return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends IdReferenceType> ) this.getItem()));
        } else {
            return null;
        }
    }

    public void setItemPolicySetIdReference(IdReferenceType target) {
        if (target!= null) {
            setItem(XmlAdapterUtils.marshallJAXBElement(IdReferenceType.class, new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "PolicySetIdReference"), JAXBElement.GlobalScope.class, target));
        }
    }

    @SuppressWarnings("unchecked")
    @ManyToOne(targetEntity = CombinerParametersType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ITEMCOMBINERPARAMETERS_POLIC_1")
    public CombinerParametersType getItemCombinerParameters() {
        if (XmlAdapterUtils.isJAXBElement(CombinerParametersType.class, new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "CombinerParameters"), JAXBElement.GlobalScope.class, this.getItem())) {
            return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends CombinerParametersType> ) this.getItem()));
        } else {
            return null;
        }
    }

    public void setItemCombinerParameters(CombinerParametersType target) {
        if (target!= null) {
            setItem(XmlAdapterUtils.marshallJAXBElement(CombinerParametersType.class, new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "CombinerParameters"), JAXBElement.GlobalScope.class, target));
        }
    }
    
    @SuppressWarnings("unchecked")
    @ManyToOne(targetEntity = PolicyType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ITEMPOLICY_POLIC_1")
    public PolicyType getItemPolicy() {
        if (XmlAdapterUtils.isJAXBElement(PolicyType.class, new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "Policy"), JAXBElement.GlobalScope.class, this.getItem())) {
            return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends PolicyType> ) this.getItem()));
        } if (XmlAdapterUtils.isJAXBElement(eu.primelife.ppl.policy.impl.PolicyType.class, new QName("http://www.primelife.eu/ppl", "Policy"), JAXBElement.GlobalScope.class, this.getItem())) {
        	return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends eu.primelife.ppl.policy.impl.PolicyType>) this.getItem()));
        } else {
            return null;
        }
    }

    public void setItemPolicy(PolicyType target) {
        if (target!= null) {
            setItem(XmlAdapterUtils.marshallJAXBElement(PolicyType.class, new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "Policy"), JAXBElement.GlobalScope.class, target));
        }
    }
    
    public void setItemPolicy(eu.primelife.ppl.policy.impl.PolicyType target) {
        if (target!= null) {
            setItem(XmlAdapterUtils.marshallJAXBElement(eu.primelife.ppl.policy.impl.PolicyType.class, new QName("http://www.primelife.eu/ppl", "Policy"), JAXBElement.GlobalScope.class, target));
        }
    }
    
    @SuppressWarnings("unchecked")
    @ManyToOne(targetEntity = PolicySetType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ITEMPOLICYSET_POLIC_1")
    public PolicySetType getItemPolicySet() {
        if (XmlAdapterUtils.isJAXBElement(PolicyType.class, new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "PolicySet"), JAXBElement.GlobalScope.class, this.getItem())) {
            return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends PolicySetType> ) this.getItem()));
        } if (XmlAdapterUtils.isJAXBElement(eu.primelife.ppl.policy.impl.PolicySetType.class, new QName("http://www.primelife.eu/ppl", "PolicySet"), JAXBElement.GlobalScope.class, this.getItem())) {
        	return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends eu.primelife.ppl.policy.impl.PolicySetType>) this.getItem()));
        } else {
            return null;
        }
    }

    public void setItemPolicySet(PolicySetType target) {
        if (target!= null) {
            setItem(XmlAdapterUtils.marshallJAXBElement(PolicySetType.class, new QName("urn:oasis:names:tc:xacml:2.0:policy:schema:os", "PolicySet"), JAXBElement.GlobalScope.class, target));
        }
    }
    
    public void setItemPolicySet(eu.primelife.ppl.policy.impl.PolicySetType target) {
        if (target!= null) {
            setItem(XmlAdapterUtils.marshallJAXBElement(eu.primelife.ppl.policy.impl.PolicySetType.class, new QName("http://www.primelife.eu/ppl", "PolicySet"), JAXBElement.GlobalScope.class, target));
        }
    }

}
