/*******************************************************************************
 * Copyright (c) 2013, SAP AG
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions 
 * are met:
 *  
 *     - Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *     - Redistributions in binary form must reproduce the above copyright 
 *      notice, this list of conditions and the following disclaimer in the 
 *      documentation and/or other materials provided with the distribution.
 *     - Neither the name of the SAP AG nor the names of its contributors may
 *      be used to endorse or promote products derived from this software 
 *      without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF 
 * THE POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.03 at 09:58:45 AM CET 
//


package eu.primelife.ppl.policy.credential.impl;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.jvnet.hyperjaxb3.item.ItemUtils;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBToStringBuilder;


/**
 * <p>Java class for AttributeMatchAnyOfType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AttributeMatchAnyOfType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;choice>
 *           &lt;element ref="{http://www.primelife.eu/ppl/credential}MatchValue" minOccurs="0"/>
 *           &lt;element ref="{http://www.primelife.eu/ppl/credential}UndisclosedExpression" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="AttributeId" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="Disclose" type="{http://www.primelife.eu/ppl/credential}DiscloseType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttributeMatchAnyOfType", propOrder = {
    "matchValueOrUndisclosedExpression"
})
@Entity(name = "eu.primelife.ppl.policy.credential.impl.AttributeMatchAnyOfType")
@Table(name = "ATTRIBUTEMATCHANYOFTYPE")
@Inheritance(strategy = InheritanceType.JOINED)
public class AttributeMatchAnyOfType implements Serializable, Equals, HashCode, ToString
{

    @XmlElements({
        @XmlElement(name = "MatchValue", type = MatchValueType.class),
        @XmlElement(name = "UndisclosedExpression", type = UndisclosedExpressionType.class)
    })
    protected List<Object> matchValueOrUndisclosedExpression;
    @XmlAttribute(name = "AttributeId", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String attributeId;
    @XmlAttribute(name = "Disclose")
    protected DiscloseType disclose;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;
    protected transient List<AttributeMatchAnyOfTypeMatchValueOrUndisclosedExpressionItem> matchValueOrUndisclosedExpressionItems;

    /**
     * Gets the value of the matchValueOrUndisclosedExpression property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the matchValueOrUndisclosedExpression property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMatchValueOrUndisclosedExpression().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MatchValueType }
     * {@link UndisclosedExpressionType }
     * 
     * 
     */
    @Transient
    public List<Object> getMatchValueOrUndisclosedExpression() {
        if (matchValueOrUndisclosedExpression == null) {
            matchValueOrUndisclosedExpression = new ArrayList<Object>();
        }
        return this.matchValueOrUndisclosedExpression;
    }

    /**
     * 
     * 
     */
    public void setMatchValueOrUndisclosedExpression(List<Object> matchValueOrUndisclosedExpression) {
        this.matchValueOrUndisclosedExpression = matchValueOrUndisclosedExpression;
    }

    /**
     * Gets the value of the attributeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "ATTRIBUTEID")
    public String getAttributeId() {
        return attributeId;
    }

    /**
     * Sets the value of the attributeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttributeId(String value) {
        this.attributeId = value;
    }

    /**
     * Gets the value of the disclose property.
     * 
     * @return
     *     possible object is
     *     {@link DiscloseType }
     *     
     */
    @Basic
    @Column(name = "DISCLOSE", length = 255)
    @Enumerated(EnumType.STRING)
    public DiscloseType getDisclose() {
        return disclose;
    }

    /**
     * Sets the value of the disclose property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiscloseType }
     *     
     */
    public void setDisclose(DiscloseType value) {
        this.disclose = value;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    @OneToMany(targetEntity = AttributeMatchAnyOfTypeMatchValueOrUndisclosedExpressionItem.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "MATCHVALUEORUNDISCLOSEDEXPRE_1")
    public List<AttributeMatchAnyOfTypeMatchValueOrUndisclosedExpressionItem> getMatchValueOrUndisclosedExpressionItems() {
        if (this.matchValueOrUndisclosedExpressionItems == null) {
            this.matchValueOrUndisclosedExpressionItems = new ArrayList<AttributeMatchAnyOfTypeMatchValueOrUndisclosedExpressionItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.matchValueOrUndisclosedExpression)) {
            this.matchValueOrUndisclosedExpression = ItemUtils.wrap(this.matchValueOrUndisclosedExpression, this.matchValueOrUndisclosedExpressionItems, AttributeMatchAnyOfTypeMatchValueOrUndisclosedExpressionItem.class);
        }
        return this.matchValueOrUndisclosedExpressionItems;
    }

    public void setMatchValueOrUndisclosedExpressionItems(List<AttributeMatchAnyOfTypeMatchValueOrUndisclosedExpressionItem> value) {
        this.matchValueOrUndisclosedExpression = null;
        this.matchValueOrUndisclosedExpressionItems = null;
        this.matchValueOrUndisclosedExpressionItems = value;
        if (this.matchValueOrUndisclosedExpressionItems == null) {
            this.matchValueOrUndisclosedExpressionItems = new ArrayList<AttributeMatchAnyOfTypeMatchValueOrUndisclosedExpressionItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.matchValueOrUndisclosedExpression)) {
            this.matchValueOrUndisclosedExpression = ItemUtils.wrap(this.matchValueOrUndisclosedExpression, this.matchValueOrUndisclosedExpressionItems, AttributeMatchAnyOfTypeMatchValueOrUndisclosedExpressionItem.class);
        }
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof AttributeMatchAnyOfType)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        final AttributeMatchAnyOfType that = ((AttributeMatchAnyOfType) object);
        equalsBuilder.append(this.getMatchValueOrUndisclosedExpression(), that.getMatchValueOrUndisclosedExpression());
        equalsBuilder.append(this.getAttributeId(), that.getAttributeId());
        equalsBuilder.append(this.getDisclose(), that.getDisclose());
    }

    public boolean equals(Object object) {
        if (!(object instanceof AttributeMatchAnyOfType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        hashCodeBuilder.append(this.getMatchValueOrUndisclosedExpression());
        hashCodeBuilder.append(this.getAttributeId());
        hashCodeBuilder.append(this.getDisclose());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

    public void toString(ToStringBuilder toStringBuilder) {
        {
            List<Object> theMatchValueOrUndisclosedExpression;
            theMatchValueOrUndisclosedExpression = this.getMatchValueOrUndisclosedExpression();
            toStringBuilder.append("matchValueOrUndisclosedExpression", theMatchValueOrUndisclosedExpression);
        }
        {
            String theAttributeId;
            theAttributeId = this.getAttributeId();
            toStringBuilder.append("attributeId", theAttributeId);
        }
        {
            DiscloseType theDisclose;
            theDisclose = this.getDisclose();
            toStringBuilder.append("disclose", theDisclose);
        }
    }

    public String toString() {
        final ToStringBuilder toStringBuilder = new JAXBToStringBuilder(this);
        toString(toStringBuilder);
        return toStringBuilder.toString();
    }

}
