/*******************************************************************************
 * Copyright (c) 2013, SAP AG
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions 
 * are met:
 *  
 *     - Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *     - Redistributions in binary form must reproduce the above copyright 
 *      notice, this list of conditions and the following disclaimer in the 
 *      documentation and/or other materials provided with the distribution.
 *     - Neither the name of the SAP AG nor the names of its contributors may
 *      be used to endorse or promote products derived from this software 
 *      without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF 
 * THE POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.03 at 09:58:45 AM CET 
//


package eu.primelife.ppl.policy.credential.impl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.primelife.ppl.policy.credential.impl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Condition_QNAME = new QName("http://www.primelife.eu/ppl/credential", "Condition");
    private final static QName _CredentialAttributeDesignator_QNAME = new QName("http://www.primelife.eu/ppl/credential", "CredentialAttributeDesignator");
    private final static QName _AttributeMatchAnyOf_QNAME = new QName("http://www.primelife.eu/ppl/credential", "AttributeMatchAnyOf");
    private final static QName _UndisclosedExpression_QNAME = new QName("http://www.primelife.eu/ppl/credential", "UndisclosedExpression");
    private final static QName _MatchValue_QNAME = new QName("http://www.primelife.eu/ppl/credential", "MatchValue");
    private final static QName _Apply_QNAME = new QName("http://www.primelife.eu/ppl/credential", "Apply");
    private final static QName _Credential_QNAME = new QName("http://www.primelife.eu/ppl/credential", "Credential");
    private final static QName _CredentialRequirements_QNAME = new QName("http://www.primelife.eu/ppl/credential", "CredentialRequirements");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.primelife.ppl.policy.credential.impl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConditionType }
     * 
     */
    public ConditionType createConditionType() {
        return new ConditionType();
    }

    /**
     * Create an instance of {@link CredentialType }
     * 
     */
    public CredentialType createCredentialType() {
        return new CredentialType();
    }

    /**
     * Create an instance of {@link AttributeMatchAnyOfType }
     * 
     */
    public AttributeMatchAnyOfType createAttributeMatchAnyOfType() {
        return new AttributeMatchAnyOfType();
    }

    /**
     * Create an instance of {@link MatchValueType }
     * 
     */
    public MatchValueType createMatchValueType() {
        return new MatchValueType();
    }

    /**
     * Create an instance of {@link CredentialAttributeDesignatorType }
     * 
     */
    public CredentialAttributeDesignatorType createCredentialAttributeDesignatorType() {
        return new CredentialAttributeDesignatorType();
    }

    /**
     * Create an instance of {@link CredentialRequirementsType }
     * 
     */
    public CredentialRequirementsType createCredentialRequirementsType() {
        return new CredentialRequirementsType();
    }

    /**
     * Create an instance of {@link PrimelifeApplyType }
     * 
     */
    public PrimelifeApplyType createPrimelifeApplyType() {
        return new PrimelifeApplyType();
    }

    /**
     * Create an instance of {@link UndisclosedExpressionType }
     * 
     */
    public UndisclosedExpressionType createUndisclosedExpressionType() {
        return new UndisclosedExpressionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConditionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/credential", name = "Condition")
    public JAXBElement<ConditionType> createCondition(ConditionType value) {
        return new JAXBElement<ConditionType>(_Condition_QNAME, ConditionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CredentialAttributeDesignatorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/credential", name = "CredentialAttributeDesignator", substitutionHeadNamespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", substitutionHeadName = "Expression")
    public JAXBElement<CredentialAttributeDesignatorType> createCredentialAttributeDesignator(CredentialAttributeDesignatorType value) {
        return new JAXBElement<CredentialAttributeDesignatorType>(_CredentialAttributeDesignator_QNAME, CredentialAttributeDesignatorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeMatchAnyOfType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/credential", name = "AttributeMatchAnyOf")
    public JAXBElement<AttributeMatchAnyOfType> createAttributeMatchAnyOf(AttributeMatchAnyOfType value) {
        return new JAXBElement<AttributeMatchAnyOfType>(_AttributeMatchAnyOf_QNAME, AttributeMatchAnyOfType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UndisclosedExpressionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/credential", name = "UndisclosedExpression", substitutionHeadNamespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", substitutionHeadName = "Expression")
    public JAXBElement<UndisclosedExpressionType> createUndisclosedExpression(UndisclosedExpressionType value) {
        return new JAXBElement<UndisclosedExpressionType>(_UndisclosedExpression_QNAME, UndisclosedExpressionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MatchValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/credential", name = "MatchValue")
    public JAXBElement<MatchValueType> createMatchValue(MatchValueType value) {
        return new JAXBElement<MatchValueType>(_MatchValue_QNAME, MatchValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrimelifeApplyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/credential", name = "Apply", substitutionHeadNamespace = "urn:oasis:names:tc:xacml:2.0:policy:schema:os", substitutionHeadName = "Apply")
    public JAXBElement<PrimelifeApplyType> createApply(PrimelifeApplyType value) {
        return new JAXBElement<PrimelifeApplyType>(_Apply_QNAME, PrimelifeApplyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CredentialType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/credential", name = "Credential")
    public JAXBElement<CredentialType> createCredential(CredentialType value) {
        return new JAXBElement<CredentialType>(_Credential_QNAME, CredentialType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CredentialRequirementsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/credential", name = "CredentialRequirements")
    public JAXBElement<CredentialRequirementsType> createCredentialRequirements(CredentialRequirementsType value) {
        return new JAXBElement<CredentialRequirementsType>(_CredentialRequirements_QNAME, CredentialRequirementsType.class, null, value);
    }

}
