/*******************************************************************************
 * Copyright (c) 2013, SAP AG
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions 
 * are met:
 *  
 *     - Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *     - Redistributions in binary form must reproduce the above copyright 
 *      notice, this list of conditions and the following disclaimer in the 
 *      documentation and/or other materials provided with the distribution.
 *     - Neither the name of the SAP AG nor the names of its contributors may
 *      be used to endorse or promote products derived from this software 
 *      without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF 
 * THE POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.03 at 09:58:45 AM CET 
//


package eu.primelife.ppl.stickypolicy.authorization.impl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.primelife.ppl.stickypolicy.authorization.impl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AuthorizationsSet_QNAME = new QName("http://www.primelife.eu/ppl/authorization/mismatch", "AuthorizationsSet");
    private final static QName _AuthorizationsMismatch_QNAME = new QName("http://www.primelife.eu/ppl/authorization/mismatch", "AuthorizationsMismatch");
    private final static QName _AuthzDownstreamUsage_QNAME = new QName("http://www.primelife.eu/ppl/authorization/mismatch", "AuthzDownstreamUsage");
    private final static QName _AuthzUseForPurpose_QNAME = new QName("http://www.primelife.eu/ppl/authorization/mismatch", "AuthzUseForPurpose");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.primelife.ppl.stickypolicy.authorization.impl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AuthzUseForPurposeMismatchType }
     * 
     */
    public AuthzUseForPurposeMismatchType createAuthzUseForPurposeMismatchType() {
        return new AuthzUseForPurposeMismatchType();
    }

    /**
     * Create an instance of {@link AuthorizationsSetMismatchType }
     * 
     */
    public AuthorizationsSetMismatchType createAuthorizationsSetMismatchType() {
        return new AuthorizationsSetMismatchType();
    }

    /**
     * Create an instance of {@link AuthorizationsMismatchType }
     * 
     */
    public AuthorizationsMismatchType createAuthorizationsMismatchType() {
        return new AuthorizationsMismatchType();
    }

    /**
     * Create an instance of {@link AuthzDownstreamUsageMismatchType }
     * 
     */
    public AuthzDownstreamUsageMismatchType createAuthzDownstreamUsageMismatchType() {
        return new AuthzDownstreamUsageMismatchType();
    }

    /**
     * Create an instance of {@link PurposeListType }
     * 
     */
    public PurposeListType createPurposeListType() {
        return new PurposeListType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizationsSetMismatchType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/authorization/mismatch", name = "AuthorizationsSet")
    public JAXBElement<AuthorizationsSetMismatchType> createAuthorizationsSet(AuthorizationsSetMismatchType value) {
        return new JAXBElement<AuthorizationsSetMismatchType>(_AuthorizationsSet_QNAME, AuthorizationsSetMismatchType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizationsMismatchType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/authorization/mismatch", name = "AuthorizationsMismatch")
    public JAXBElement<AuthorizationsMismatchType> createAuthorizationsMismatch(AuthorizationsMismatchType value) {
        return new JAXBElement<AuthorizationsMismatchType>(_AuthorizationsMismatch_QNAME, AuthorizationsMismatchType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthzDownstreamUsageMismatchType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/authorization/mismatch", name = "AuthzDownstreamUsage")
    public JAXBElement<AuthzDownstreamUsageMismatchType> createAuthzDownstreamUsage(AuthzDownstreamUsageMismatchType value) {
        return new JAXBElement<AuthzDownstreamUsageMismatchType>(_AuthzDownstreamUsage_QNAME, AuthzDownstreamUsageMismatchType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthzUseForPurposeMismatchType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/authorization/mismatch", name = "AuthzUseForPurpose")
    public JAXBElement<AuthzUseForPurposeMismatchType> createAuthzUseForPurpose(AuthzUseForPurposeMismatchType value) {
        return new JAXBElement<AuthzUseForPurposeMismatchType>(_AuthzUseForPurpose_QNAME, AuthzUseForPurposeMismatchType.class, null, value);
    }

}
