/*******************************************************************************
 * Copyright (c) 2013, SAP AG
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions 
 * are met:
 *  
 *     - Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *     - Redistributions in binary form must reproduce the above copyright 
 *      notice, this list of conditions and the following disclaimer in the 
 *      documentation and/or other materials provided with the distribution.
 *     - Neither the name of the SAP AG nor the names of its contributors may
 *      be used to endorse or promote products derived from this software 
 *      without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF 
 * THE POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.03 at 09:58:45 AM CET 
//


package org.w3._2000._09.xmldsig_;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.namespace.QName;
import org.jvnet.hyperjaxb3.item.MixedItem;
import org.jvnet.hyperjaxb3.xml.bind.JAXBContextUtils;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.ElementAsString;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XmlAdapterUtils;
import org.w3c.dom.Element;

@XmlAccessorType(XmlAccessType.FIELD)
@Entity(name = "org.w3._2000._09.xmldsig_.KeyInfoTypeContentItem")
@Table(name = "KEYINFOTYPECONTENTITEM")
@Inheritance(strategy = InheritanceType.JOINED)
public class KeyInfoTypeContentItem
    implements Serializable, MixedItem<Object>
{

    @XmlElementRefs({
        @XmlElementRef(name = "PGPData", namespace = "http://www.w3.org/2000/09/xmldsig#", type = JAXBElement.class),
        @XmlElementRef(name = "SPKIData", namespace = "http://www.w3.org/2000/09/xmldsig#", type = JAXBElement.class),
        @XmlElementRef(name = "MgmtData", namespace = "http://www.w3.org/2000/09/xmldsig#", type = JAXBElement.class),
        @XmlElementRef(name = "KeyName", namespace = "http://www.w3.org/2000/09/xmldsig#", type = JAXBElement.class),
        @XmlElementRef(name = "RetrievalMethod", namespace = "http://www.w3.org/2000/09/xmldsig#", type = JAXBElement.class),
        @XmlElementRef(name = "KeyValue", namespace = "http://www.w3.org/2000/09/xmldsig#", type = JAXBElement.class),
        @XmlElementRef(name = "X509Data", namespace = "http://www.w3.org/2000/09/xmldsig#", type = JAXBElement.class)
    })
    @XmlAnyElement(lax = true)
    protected Object item;
    @XmlAttribute(name = "Text")
    protected String text;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * 
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PGPDataType }{@code >}
     *     {@link Object }
     *     {@link JAXBElement }{@code <}{@link SPKIDataType }{@code >}
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     {@link Element }
     *     {@link JAXBElement }{@code <}{@link RetrievalMethodType }{@code >}
     *     {@link JAXBElement }{@code <}{@link KeyValueType }{@code >}
     *     {@link JAXBElement }{@code <}{@link X509DataType }{@code >}
     *     
     */
    @Transient
    public Object getItem() {
        return item;
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PGPDataType }{@code >}
     *     {@link Object }
     *     {@link JAXBElement }{@code <}{@link SPKIDataType }{@code >}
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     {@link Element }
     *     {@link JAXBElement }{@code <}{@link RetrievalMethodType }{@code >}
     *     {@link JAXBElement }{@code <}{@link KeyValueType }{@code >}
     *     {@link JAXBElement }{@code <}{@link X509DataType }{@code >}
     *     
     */
    public void setItem(Object value) {
        this.item = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "TEXT")
    @Lob
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    @Basic
    @Column(name = "ITEMELEMENT")
    @Lob
    public String getItemElement() {
        if (this.getItem() instanceof Element) {
            return XmlAdapterUtils.unmarshall(ElementAsString.class, ((Element) this.getItem()));
        } else {
            return null;
        }
    }

    public void setItemElement(String target) {
        if (target!= null) {
            setItem(XmlAdapterUtils.marshall(ElementAsString.class, target));
        }
    }

    @Basic
    @Column(name = "ITEMOBJECT")
    @Lob
    public String getItemObject() {
        if ((!((((((XmlAdapterUtils.isJAXBElement(PGPDataType.class, new QName("http://www.w3.org/2000/09/xmldsig#", "PGPData"), JAXBElement.GlobalScope.class, this.getItem())||XmlAdapterUtils.isJAXBElement(SPKIDataType.class, new QName("http://www.w3.org/2000/09/xmldsig#", "SPKIData"), JAXBElement.GlobalScope.class, this.getItem()))||XmlAdapterUtils.isJAXBElement(String.class, new QName("http://www.w3.org/2000/09/xmldsig#", "MgmtData"), JAXBElement.GlobalScope.class, this.getItem()))||XmlAdapterUtils.isJAXBElement(String.class, new QName("http://www.w3.org/2000/09/xmldsig#", "KeyName"), JAXBElement.GlobalScope.class, this.getItem()))||XmlAdapterUtils.isJAXBElement(RetrievalMethodType.class, new QName("http://www.w3.org/2000/09/xmldsig#", "RetrievalMethod"), JAXBElement.GlobalScope.class, this.getItem()))||XmlAdapterUtils.isJAXBElement(KeyValueType.class, new QName("http://www.w3.org/2000/09/xmldsig#", "KeyValue"), JAXBElement.GlobalScope.class, this.getItem()))||XmlAdapterUtils.isJAXBElement(X509DataType.class, new QName("http://www.w3.org/2000/09/xmldsig#", "X509Data"), JAXBElement.GlobalScope.class, this.getItem())))&&JAXBContextUtils.isElement("eu.primelife.ppl.claims.impl:eu.primelife.ppl.stickypolicy.obligation.impl:eu.primelife.ppl.policy.obligation.impl:oasis.names.tc.xacml._2_0.context.schema.os:eu.primelife.ppl.stickypolicy.impl:eu.primelife.ppl.pii.impl:eu.primelife.ppl.policy.credential.impl:eu.primelife.ppl.policy.impl:org.w3._2000._09.xmldsig_:eu.primelife.ppl.policy.xacml.impl:oasis.names.tc.saml._2_0.assertion:eu.primelife.ppl.stickypolicy.authorization.impl:org.w3._2001._04.xmlenc_", this.getItem())) {
            return JAXBContextUtils.unmarshall("eu.primelife.ppl.claims.impl:eu.primelife.ppl.stickypolicy.obligation.impl:eu.primelife.ppl.policy.obligation.impl:oasis.names.tc.xacml._2_0.context.schema.os:eu.primelife.ppl.stickypolicy.impl:eu.primelife.ppl.pii.impl:eu.primelife.ppl.policy.credential.impl:eu.primelife.ppl.policy.impl:org.w3._2000._09.xmldsig_:eu.primelife.ppl.policy.xacml.impl:oasis.names.tc.saml._2_0.assertion:eu.primelife.ppl.stickypolicy.authorization.impl:org.w3._2001._04.xmlenc_", this.getItem());
        } else {
            return null;
        }
    }

    public void setItemObject(String target) {
        if (target!= null) {
            setItem(JAXBContextUtils.marshall("eu.primelife.ppl.claims.impl:eu.primelife.ppl.stickypolicy.obligation.impl:eu.primelife.ppl.policy.obligation.impl:oasis.names.tc.xacml._2_0.context.schema.os:eu.primelife.ppl.stickypolicy.impl:eu.primelife.ppl.pii.impl:eu.primelife.ppl.policy.credential.impl:eu.primelife.ppl.policy.impl:org.w3._2000._09.xmldsig_:eu.primelife.ppl.policy.xacml.impl:oasis.names.tc.saml._2_0.assertion:eu.primelife.ppl.stickypolicy.authorization.impl:org.w3._2001._04.xmlenc_", target));
        }
    }

    @SuppressWarnings("unchecked")
    @ManyToOne(targetEntity = PGPDataType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ITEMPGPDATA_KEYINFOTYPECONTE_0")
    public PGPDataType getItemPGPData() {
        if (XmlAdapterUtils.isJAXBElement(PGPDataType.class, new QName("http://www.w3.org/2000/09/xmldsig#", "PGPData"), JAXBElement.GlobalScope.class, this.getItem())) {
            return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends PGPDataType> ) this.getItem()));
        } else {
            return null;
        }
    }

    public void setItemPGPData(PGPDataType target) {
        if (target!= null) {
            setItem(XmlAdapterUtils.marshallJAXBElement(PGPDataType.class, new QName("http://www.w3.org/2000/09/xmldsig#", "PGPData"), JAXBElement.GlobalScope.class, target));
        }
    }

    @SuppressWarnings("unchecked")
    @ManyToOne(targetEntity = SPKIDataType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ITEMSPKIDATA_KEYINFOTYPECONT_0")
    public SPKIDataType getItemSPKIData() {
        if (XmlAdapterUtils.isJAXBElement(SPKIDataType.class, new QName("http://www.w3.org/2000/09/xmldsig#", "SPKIData"), JAXBElement.GlobalScope.class, this.getItem())) {
            return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends SPKIDataType> ) this.getItem()));
        } else {
            return null;
        }
    }

    public void setItemSPKIData(SPKIDataType target) {
        if (target!= null) {
            setItem(XmlAdapterUtils.marshallJAXBElement(SPKIDataType.class, new QName("http://www.w3.org/2000/09/xmldsig#", "SPKIData"), JAXBElement.GlobalScope.class, target));
        }
    }

    @SuppressWarnings("unchecked")
    @Basic
    @Column(name = "ITEMMGMTDATA")
    public String getItemMgmtData() {
        if (XmlAdapterUtils.isJAXBElement(String.class, new QName("http://www.w3.org/2000/09/xmldsig#", "MgmtData"), JAXBElement.GlobalScope.class, this.getItem())) {
            return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends String> ) this.getItem()));
        } else {
            return null;
        }
    }

    public void setItemMgmtData(String target) {
        if (target!= null) {
            setItem(XmlAdapterUtils.marshallJAXBElement(String.class, new QName("http://www.w3.org/2000/09/xmldsig#", "MgmtData"), JAXBElement.GlobalScope.class, target));
        }
    }

    @SuppressWarnings("unchecked")
    @Basic
    @Column(name = "ITEMKEYNAME")
    public String getItemKeyName() {
        if (XmlAdapterUtils.isJAXBElement(String.class, new QName("http://www.w3.org/2000/09/xmldsig#", "KeyName"), JAXBElement.GlobalScope.class, this.getItem())) {
            return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends String> ) this.getItem()));
        } else {
            return null;
        }
    }

    public void setItemKeyName(String target) {
        if (target!= null) {
            setItem(XmlAdapterUtils.marshallJAXBElement(String.class, new QName("http://www.w3.org/2000/09/xmldsig#", "KeyName"), JAXBElement.GlobalScope.class, target));
        }
    }
    
    @SuppressWarnings("unchecked")
    @ManyToOne(targetEntity = RetrievalMethodType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ITEMRETRIEVALMETHOD_KEYINFOT_0")
    public RetrievalMethodType getItemRetrievalMethod() {
        if (XmlAdapterUtils.isJAXBElement(RetrievalMethodType.class, new QName("http://www.w3.org/2000/09/xmldsig#", "RetrievalMethod"), JAXBElement.GlobalScope.class, this.getItem())) {
            return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends RetrievalMethodType> ) this.getItem()));
        } else {
            return null;
        }
    }

    public void setItemRetrievalMethod(RetrievalMethodType target) {
        if (target!= null) {
            setItem(XmlAdapterUtils.marshallJAXBElement(RetrievalMethodType.class, new QName("http://www.w3.org/2000/09/xmldsig#", "RetrievalMethod"), JAXBElement.GlobalScope.class, target));
        }
    }

    @SuppressWarnings("unchecked")
    @ManyToOne(targetEntity = KeyValueType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ITEMKEYVALUE_KEYINFOTYPECONT_0")
    public KeyValueType getItemKeyValue() {
        if (XmlAdapterUtils.isJAXBElement(KeyValueType.class, new QName("http://www.w3.org/2000/09/xmldsig#", "KeyValue"), JAXBElement.GlobalScope.class, this.getItem())) {
            return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends KeyValueType> ) this.getItem()));
        } else {
            return null;
        }
    }

    public void setItemKeyValue(KeyValueType target) {
        if (target!= null) {
            setItem(XmlAdapterUtils.marshallJAXBElement(KeyValueType.class, new QName("http://www.w3.org/2000/09/xmldsig#", "KeyValue"), JAXBElement.GlobalScope.class, target));
        }
    }

    @SuppressWarnings("unchecked")
	@ManyToOne(targetEntity = X509DataType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ITEMX509DATA_KEYINFOTYPECONT_0")
    public X509DataType getItemX509Data() {
        if (XmlAdapterUtils.isJAXBElement(X509DataType.class, new QName("http://www.w3.org/2000/09/xmldsig#", "X509Data"), JAXBElement.GlobalScope.class, this.getItem())) {
            return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends X509DataType> ) this.getItem()));
        } else {
            return null;
        }
    }

    public void setItemX509Data(X509DataType target) {
        if (target!= null) {
            setItem(XmlAdapterUtils.marshallJAXBElement(X509DataType.class, new QName("http://www.w3.org/2000/09/xmldsig#", "X509Data"), JAXBElement.GlobalScope.class, target));
        }
    }

}
