/*******************************************************************************
 * Copyright (c) 2013, SAP AG
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions 
 * are met:
 *  
 *     - Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *     - Redistributions in binary form must reproduce the above copyright 
 *      notice, this list of conditions and the following disclaimer in the 
 *      documentation and/or other materials provided with the distribution.
 *     - Neither the name of the SAP AG nor the names of its contributors may
 *      be used to endorse or promote products derived from this software 
 *      without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF 
 * THE POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.03 at 09:58:45 AM CET 
//


package eu.primelife.ppl.stickypolicy.obligation.impl;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import eu.primelife.ppl.policy.obligation.impl.ActionAnonymizePersonalData;
import eu.primelife.ppl.policy.obligation.impl.ActionDeletePersonalData;
import eu.primelife.ppl.policy.obligation.impl.ActionLog;
import eu.primelife.ppl.policy.obligation.impl.ActionNotifyDataSubject;
import eu.primelife.ppl.policy.obligation.impl.ActionSecureLog;
import eu.primelife.ppl.policy.obligation.impl.DateAndTime;
import eu.primelife.ppl.policy.obligation.impl.Duration;
import eu.primelife.ppl.policy.obligation.impl.Obligation;
import eu.primelife.ppl.policy.obligation.impl.TriggerAtTime;
import eu.primelife.ppl.policy.obligation.impl.TriggerDataLost;
import eu.primelife.ppl.policy.obligation.impl.TriggerDataSubjectAccess;
import eu.primelife.ppl.policy.obligation.impl.TriggerOnViolation;
import eu.primelife.ppl.policy.obligation.impl.TriggerPeriodic;
import eu.primelife.ppl.policy.obligation.impl.TriggerPersonalDataAccessedForPurpose;
import eu.primelife.ppl.policy.obligation.impl.TriggerPersonalDataDeleted;
import eu.primelife.ppl.policy.obligation.impl.TriggerPersonalDataSent;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBToStringBuilder;


/**
 * <p>Java class for MismatchPolicy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MismatchPolicy">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.primelife.eu/ppl/obligation}Obligation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.primelife.eu/ppl/obligation}TriggerAtTime" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.primelife.eu/ppl/obligation}DateAndTime" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.primelife.eu/ppl/obligation}Duration" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.primelife.eu/ppl/obligation}TriggerPeriodic" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.primelife.eu/ppl/obligation}TriggerPersonalDataAccessedForPurpose" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.primelife.eu/ppl/obligation}TriggerPersonalDataDeleted" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.primelife.eu/ppl/obligation}TriggerPersonalDataSent" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.primelife.eu/ppl/obligation}TriggerDataSubjectAccess" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.primelife.eu/ppl/obligation}TriggerDataLost" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.primelife.eu/ppl/obligation}TriggerOnViolation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.primelife.eu/ppl/obligation}ActionDeletePersonalData" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.primelife.eu/ppl/obligation}ActionAnonymizePersonalData" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.primelife.eu/ppl/obligation}ActionNotifyDataSubject" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.primelife.eu/ppl/obligation}ActionLog" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.primelife.eu/ppl/obligation}ActionSecureLog" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="elementId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MismatchPolicy", propOrder = {
    "obligation",
    "triggerAtTime",
    "dateAndTime",
    "duration",
    "triggerPeriodic",
    "triggerPersonalDataAccessedForPurpose",
    "triggerPersonalDataDeleted",
    "triggerPersonalDataSent",
    "triggerDataSubjectAccess",
    "triggerDataLost",
    "triggerOnViolation",
    "actionDeletePersonalData",
    "actionAnonymizePersonalData",
    "actionNotifyDataSubject",
    "actionLog",
    "actionSecureLog"
})
@Entity(name = "eu.primelife.ppl.stickypolicy.obligation.impl.MismatchPolicy")
@Table(name = "MISMATCHPOLICY")
@Inheritance(strategy = InheritanceType.JOINED)
public class MismatchPolicy
    implements Serializable, Equals, HashCode, ToString
{

    @XmlElement(name = "Obligation", namespace = "http://www.primelife.eu/ppl/obligation")
    protected List<Obligation> obligation;
    @XmlElement(name = "TriggerAtTime", namespace = "http://www.primelife.eu/ppl/obligation")
    protected List<TriggerAtTime> triggerAtTime;
    @XmlElement(name = "DateAndTime", namespace = "http://www.primelife.eu/ppl/obligation")
    protected List<DateAndTime> dateAndTime;
    @XmlElement(name = "Duration", namespace = "http://www.primelife.eu/ppl/obligation")
    protected List<Duration> duration;
    @XmlElement(name = "TriggerPeriodic", namespace = "http://www.primelife.eu/ppl/obligation")
    protected List<TriggerPeriodic> triggerPeriodic;
    @XmlElement(name = "TriggerPersonalDataAccessedForPurpose", namespace = "http://www.primelife.eu/ppl/obligation")
    protected List<TriggerPersonalDataAccessedForPurpose> triggerPersonalDataAccessedForPurpose;
    @XmlElement(name = "TriggerPersonalDataDeleted", namespace = "http://www.primelife.eu/ppl/obligation")
    protected List<TriggerPersonalDataDeleted> triggerPersonalDataDeleted;
    @XmlElement(name = "TriggerPersonalDataSent", namespace = "http://www.primelife.eu/ppl/obligation")
    protected List<TriggerPersonalDataSent> triggerPersonalDataSent;
    @XmlElement(name = "TriggerDataSubjectAccess", namespace = "http://www.primelife.eu/ppl/obligation")
    protected List<TriggerDataSubjectAccess> triggerDataSubjectAccess;
    @XmlElement(name = "TriggerDataLost", namespace = "http://www.primelife.eu/ppl/obligation")
    protected List<TriggerDataLost> triggerDataLost;
    @XmlElement(name = "TriggerOnViolation", namespace = "http://www.primelife.eu/ppl/obligation")
    protected List<TriggerOnViolation> triggerOnViolation;
    @XmlElement(name = "ActionDeletePersonalData", namespace = "http://www.primelife.eu/ppl/obligation")
    protected List<ActionDeletePersonalData> actionDeletePersonalData;
    @XmlElement(name = "ActionAnonymizePersonalData", namespace = "http://www.primelife.eu/ppl/obligation")
    protected List<ActionAnonymizePersonalData> actionAnonymizePersonalData;
    @XmlElement(name = "ActionNotifyDataSubject", namespace = "http://www.primelife.eu/ppl/obligation")
    protected List<ActionNotifyDataSubject> actionNotifyDataSubject;
    @XmlElement(name = "ActionLog", namespace = "http://www.primelife.eu/ppl/obligation")
    protected List<ActionLog> actionLog;
    @XmlElement(name = "ActionSecureLog", namespace = "http://www.primelife.eu/ppl/obligation")
    protected List<ActionSecureLog> actionSecureLog;
    @XmlAttribute
    protected String elementId;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the obligation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the obligation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObligation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Obligation }
     * 
     * 
     */
    @OneToMany(targetEntity = Obligation.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "OBLIGATION_MISMATCHPOLICY_HJ_0")
    public List<Obligation> getObligation() {
        if (obligation == null) {
            obligation = new ArrayList<Obligation>();
        }
        return this.obligation;
    }

    /**
     * 
     * 
     */
    public void setObligation(List<Obligation> obligation) {
        this.obligation = obligation;
    }

    /**
     * Gets the value of the triggerAtTime property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the triggerAtTime property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTriggerAtTime().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TriggerAtTime }
     * 
     * 
     */
    @OneToMany(targetEntity = TriggerAtTime.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "TRIGGERATTIME_MISMATCHPOLICY_0")
    public List<TriggerAtTime> getTriggerAtTime() {
        if (triggerAtTime == null) {
            triggerAtTime = new ArrayList<TriggerAtTime>();
        }
        return this.triggerAtTime;
    }

    /**
     * 
     * 
     */
    public void setTriggerAtTime(List<TriggerAtTime> triggerAtTime) {
        this.triggerAtTime = triggerAtTime;
    }

    /**
     * Gets the value of the dateAndTime property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dateAndTime property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDateAndTime().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DateAndTime }
     * 
     * 
     */
    @OneToMany(targetEntity = DateAndTime.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "DATEANDTIME_MISMATCHPOLICY_H_0")
    public List<DateAndTime> getDateAndTime() {
        if (dateAndTime == null) {
            dateAndTime = new ArrayList<DateAndTime>();
        }
        return this.dateAndTime;
    }

    /**
     * 
     * 
     */
    public void setDateAndTime(List<DateAndTime> dateAndTime) {
        this.dateAndTime = dateAndTime;
    }

    /**
     * Gets the value of the duration property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the duration property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDuration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Duration }
     * 
     * 
     */
    @OneToMany(targetEntity = Duration.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "DURATION_MISMATCHPOLICY_HJID")
    public List<Duration> getDuration() {
        if (duration == null) {
            duration = new ArrayList<Duration>();
        }
        return this.duration;
    }

    /**
     * 
     * 
     */
    public void setDuration(List<Duration> duration) {
        this.duration = duration;
    }

    /**
     * Gets the value of the triggerPeriodic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the triggerPeriodic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTriggerPeriodic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TriggerPeriodic }
     * 
     * 
     */
    @OneToMany(targetEntity = TriggerPeriodic.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "TRIGGERPERIODIC_MISMATCHPOLI_0")
    public List<TriggerPeriodic> getTriggerPeriodic() {
        if (triggerPeriodic == null) {
            triggerPeriodic = new ArrayList<TriggerPeriodic>();
        }
        return this.triggerPeriodic;
    }

    /**
     * 
     * 
     */
    public void setTriggerPeriodic(List<TriggerPeriodic> triggerPeriodic) {
        this.triggerPeriodic = triggerPeriodic;
    }

    /**
     * Gets the value of the triggerPersonalDataAccessedForPurpose property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the triggerPersonalDataAccessedForPurpose property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTriggerPersonalDataAccessedForPurpose().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TriggerPersonalDataAccessedForPurpose }
     * 
     * 
     */
    @OneToMany(targetEntity = TriggerPersonalDataAccessedForPurpose.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "TRIGGERPERSONALDATAACCESSEDF_2")
    public List<TriggerPersonalDataAccessedForPurpose> getTriggerPersonalDataAccessedForPurpose() {
        if (triggerPersonalDataAccessedForPurpose == null) {
            triggerPersonalDataAccessedForPurpose = new ArrayList<TriggerPersonalDataAccessedForPurpose>();
        }
        return this.triggerPersonalDataAccessedForPurpose;
    }

    /**
     * 
     * 
     */
    public void setTriggerPersonalDataAccessedForPurpose(List<TriggerPersonalDataAccessedForPurpose> triggerPersonalDataAccessedForPurpose) {
        this.triggerPersonalDataAccessedForPurpose = triggerPersonalDataAccessedForPurpose;
    }

    /**
     * Gets the value of the triggerPersonalDataDeleted property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the triggerPersonalDataDeleted property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTriggerPersonalDataDeleted().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TriggerPersonalDataDeleted }
     * 
     * 
     */
    @OneToMany(targetEntity = TriggerPersonalDataDeleted.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "TRIGGERPERSONALDATADELETED_M_0")
    public List<TriggerPersonalDataDeleted> getTriggerPersonalDataDeleted() {
        if (triggerPersonalDataDeleted == null) {
            triggerPersonalDataDeleted = new ArrayList<TriggerPersonalDataDeleted>();
        }
        return this.triggerPersonalDataDeleted;
    }

    /**
     * 
     * 
     */
    public void setTriggerPersonalDataDeleted(List<TriggerPersonalDataDeleted> triggerPersonalDataDeleted) {
        this.triggerPersonalDataDeleted = triggerPersonalDataDeleted;
    }

    /**
     * Gets the value of the triggerPersonalDataSent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the triggerPersonalDataSent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTriggerPersonalDataSent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TriggerPersonalDataSent }
     * 
     * 
     */
    @OneToMany(targetEntity = TriggerPersonalDataSent.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "TRIGGERPERSONALDATASENT_MISM_0")
    public List<TriggerPersonalDataSent> getTriggerPersonalDataSent() {
        if (triggerPersonalDataSent == null) {
            triggerPersonalDataSent = new ArrayList<TriggerPersonalDataSent>();
        }
        return this.triggerPersonalDataSent;
    }

    /**
     * 
     * 
     */
    public void setTriggerPersonalDataSent(List<TriggerPersonalDataSent> triggerPersonalDataSent) {
        this.triggerPersonalDataSent = triggerPersonalDataSent;
    }

    /**
     * Gets the value of the triggerDataSubjectAccess property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the triggerDataSubjectAccess property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTriggerDataSubjectAccess().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TriggerDataSubjectAccess }
     * 
     * 
     */
    @OneToMany(targetEntity = TriggerDataSubjectAccess.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "TRIGGERDATASUBJECTACCESS_MIS_0")
    public List<TriggerDataSubjectAccess> getTriggerDataSubjectAccess() {
        if (triggerDataSubjectAccess == null) {
            triggerDataSubjectAccess = new ArrayList<TriggerDataSubjectAccess>();
        }
        return this.triggerDataSubjectAccess;
    }

    /**
     * 
     * 
     */
    public void setTriggerDataSubjectAccess(List<TriggerDataSubjectAccess> triggerDataSubjectAccess) {
        this.triggerDataSubjectAccess = triggerDataSubjectAccess;
    }

    /**
     * Gets the value of the triggerDataLost property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the triggerDataLost property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTriggerDataLost().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TriggerDataLost }
     * 
     * 
     */
    @OneToMany(targetEntity = TriggerDataLost.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "TRIGGERDATALOST_MISMATCHPOLI_0")
    public List<TriggerDataLost> getTriggerDataLost() {
        if (triggerDataLost == null) {
            triggerDataLost = new ArrayList<TriggerDataLost>();
        }
        return this.triggerDataLost;
    }

    /**
     * 
     * 
     */
    public void setTriggerDataLost(List<TriggerDataLost> triggerDataLost) {
        this.triggerDataLost = triggerDataLost;
    }

    /**
     * Gets the value of the triggerOnViolation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the triggerOnViolation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTriggerOnViolation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TriggerOnViolation }
     * 
     * 
     */
    @OneToMany(targetEntity = TriggerOnViolation.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "TRIGGERONVIOLATION_MISMATCHP_0")
    public List<TriggerOnViolation> getTriggerOnViolation() {
        if (triggerOnViolation == null) {
            triggerOnViolation = new ArrayList<TriggerOnViolation>();
        }
        return this.triggerOnViolation;
    }

    /**
     * 
     * 
     */
    public void setTriggerOnViolation(List<TriggerOnViolation> triggerOnViolation) {
        this.triggerOnViolation = triggerOnViolation;
    }

    /**
     * Gets the value of the actionDeletePersonalData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the actionDeletePersonalData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActionDeletePersonalData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActionDeletePersonalData }
     * 
     * 
     */
    @OneToMany(targetEntity = ActionDeletePersonalData.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ACTIONDELETEPERSONALDATA_MIS_0")
    public List<ActionDeletePersonalData> getActionDeletePersonalData() {
        if (actionDeletePersonalData == null) {
            actionDeletePersonalData = new ArrayList<ActionDeletePersonalData>();
        }
        return this.actionDeletePersonalData;
    }

    /**
     * 
     * 
     */
    public void setActionDeletePersonalData(List<ActionDeletePersonalData> actionDeletePersonalData) {
        this.actionDeletePersonalData = actionDeletePersonalData;
    }

    /**
     * Gets the value of the actionAnonymizePersonalData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the actionAnonymizePersonalData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActionAnonymizePersonalData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActionAnonymizePersonalData }
     * 
     * 
     */
    @OneToMany(targetEntity = ActionAnonymizePersonalData.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ACTIONANONYMIZEPERSONALDATA__0")
    public List<ActionAnonymizePersonalData> getActionAnonymizePersonalData() {
        if (actionAnonymizePersonalData == null) {
            actionAnonymizePersonalData = new ArrayList<ActionAnonymizePersonalData>();
        }
        return this.actionAnonymizePersonalData;
    }

    /**
     * 
     * 
     */
    public void setActionAnonymizePersonalData(List<ActionAnonymizePersonalData> actionAnonymizePersonalData) {
        this.actionAnonymizePersonalData = actionAnonymizePersonalData;
    }

    /**
     * Gets the value of the actionNotifyDataSubject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the actionNotifyDataSubject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActionNotifyDataSubject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActionNotifyDataSubject }
     * 
     * 
     */
    @OneToMany(targetEntity = ActionNotifyDataSubject.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ACTIONNOTIFYDATASUBJECT_MISM_0")
    public List<ActionNotifyDataSubject> getActionNotifyDataSubject() {
        if (actionNotifyDataSubject == null) {
            actionNotifyDataSubject = new ArrayList<ActionNotifyDataSubject>();
        }
        return this.actionNotifyDataSubject;
    }

    /**
     * 
     * 
     */
    public void setActionNotifyDataSubject(List<ActionNotifyDataSubject> actionNotifyDataSubject) {
        this.actionNotifyDataSubject = actionNotifyDataSubject;
    }

    /**
     * Gets the value of the actionLog property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the actionLog property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActionLog().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActionLog }
     * 
     * 
     */
    @OneToMany(targetEntity = ActionLog.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ACTIONLOG_MISMATCHPOLICY_HJID")
    public List<ActionLog> getActionLog() {
        if (actionLog == null) {
            actionLog = new ArrayList<ActionLog>();
        }
        return this.actionLog;
    }

    /**
     * 
     * 
     */
    public void setActionLog(List<ActionLog> actionLog) {
        this.actionLog = actionLog;
    }

    /**
     * Gets the value of the actionSecureLog property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the actionSecureLog property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActionSecureLog().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActionSecureLog }
     * 
     * 
     */
    @OneToMany(targetEntity = ActionSecureLog.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ACTIONSECURELOG_MISMATCHPOLI_0")
    public List<ActionSecureLog> getActionSecureLog() {
        if (actionSecureLog == null) {
            actionSecureLog = new ArrayList<ActionSecureLog>();
        }
        return this.actionSecureLog;
    }

    /**
     * 
     * 
     */
    public void setActionSecureLog(List<ActionSecureLog> actionSecureLog) {
        this.actionSecureLog = actionSecureLog;
    }

    /**
     * Gets the value of the elementId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "ELEMENTID", length = 255)
    public String getElementId() {
        return elementId;
    }

    /**
     * Sets the value of the elementId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementId(String value) {
        this.elementId = value;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof MismatchPolicy)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        final MismatchPolicy that = ((MismatchPolicy) object);
        equalsBuilder.append(this.getObligation(), that.getObligation());
        equalsBuilder.append(this.getTriggerAtTime(), that.getTriggerAtTime());
        equalsBuilder.append(this.getDateAndTime(), that.getDateAndTime());
        equalsBuilder.append(this.getDuration(), that.getDuration());
        equalsBuilder.append(this.getTriggerPeriodic(), that.getTriggerPeriodic());
        equalsBuilder.append(this.getTriggerPersonalDataAccessedForPurpose(), that.getTriggerPersonalDataAccessedForPurpose());
        equalsBuilder.append(this.getTriggerPersonalDataDeleted(), that.getTriggerPersonalDataDeleted());
        equalsBuilder.append(this.getTriggerPersonalDataSent(), that.getTriggerPersonalDataSent());
        equalsBuilder.append(this.getTriggerDataSubjectAccess(), that.getTriggerDataSubjectAccess());
        equalsBuilder.append(this.getTriggerDataLost(), that.getTriggerDataLost());
        equalsBuilder.append(this.getTriggerOnViolation(), that.getTriggerOnViolation());
        equalsBuilder.append(this.getActionDeletePersonalData(), that.getActionDeletePersonalData());
        equalsBuilder.append(this.getActionAnonymizePersonalData(), that.getActionAnonymizePersonalData());
        equalsBuilder.append(this.getActionNotifyDataSubject(), that.getActionNotifyDataSubject());
        equalsBuilder.append(this.getActionLog(), that.getActionLog());
        equalsBuilder.append(this.getActionSecureLog(), that.getActionSecureLog());
        equalsBuilder.append(this.getElementId(), that.getElementId());
    }

    public boolean equals(Object object) {
        if (!(object instanceof MismatchPolicy)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        hashCodeBuilder.append(this.getObligation());
        hashCodeBuilder.append(this.getTriggerAtTime());
        hashCodeBuilder.append(this.getDateAndTime());
        hashCodeBuilder.append(this.getDuration());
        hashCodeBuilder.append(this.getTriggerPeriodic());
        hashCodeBuilder.append(this.getTriggerPersonalDataAccessedForPurpose());
        hashCodeBuilder.append(this.getTriggerPersonalDataDeleted());
        hashCodeBuilder.append(this.getTriggerPersonalDataSent());
        hashCodeBuilder.append(this.getTriggerDataSubjectAccess());
        hashCodeBuilder.append(this.getTriggerDataLost());
        hashCodeBuilder.append(this.getTriggerOnViolation());
        hashCodeBuilder.append(this.getActionDeletePersonalData());
        hashCodeBuilder.append(this.getActionAnonymizePersonalData());
        hashCodeBuilder.append(this.getActionNotifyDataSubject());
        hashCodeBuilder.append(this.getActionLog());
        hashCodeBuilder.append(this.getActionSecureLog());
        hashCodeBuilder.append(this.getElementId());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

    public void toString(ToStringBuilder toStringBuilder) {
        {
            List<Obligation> theObligation;
            theObligation = this.getObligation();
            toStringBuilder.append("obligation", theObligation);
        }
        {
            List<TriggerAtTime> theTriggerAtTime;
            theTriggerAtTime = this.getTriggerAtTime();
            toStringBuilder.append("triggerAtTime", theTriggerAtTime);
        }
        {
            List<DateAndTime> theDateAndTime;
            theDateAndTime = this.getDateAndTime();
            toStringBuilder.append("dateAndTime", theDateAndTime);
        }
        {
            List<Duration> theDuration;
            theDuration = this.getDuration();
            toStringBuilder.append("duration", theDuration);
        }
        {
            List<TriggerPeriodic> theTriggerPeriodic;
            theTriggerPeriodic = this.getTriggerPeriodic();
            toStringBuilder.append("triggerPeriodic", theTriggerPeriodic);
        }
        {
            List<TriggerPersonalDataAccessedForPurpose> theTriggerPersonalDataAccessedForPurpose;
            theTriggerPersonalDataAccessedForPurpose = this.getTriggerPersonalDataAccessedForPurpose();
            toStringBuilder.append("triggerPersonalDataAccessedForPurpose", theTriggerPersonalDataAccessedForPurpose);
        }
        {
            List<TriggerPersonalDataDeleted> theTriggerPersonalDataDeleted;
            theTriggerPersonalDataDeleted = this.getTriggerPersonalDataDeleted();
            toStringBuilder.append("triggerPersonalDataDeleted", theTriggerPersonalDataDeleted);
        }
        {
            List<TriggerPersonalDataSent> theTriggerPersonalDataSent;
            theTriggerPersonalDataSent = this.getTriggerPersonalDataSent();
            toStringBuilder.append("triggerPersonalDataSent", theTriggerPersonalDataSent);
        }
        {
            List<TriggerDataSubjectAccess> theTriggerDataSubjectAccess;
            theTriggerDataSubjectAccess = this.getTriggerDataSubjectAccess();
            toStringBuilder.append("triggerDataSubjectAccess", theTriggerDataSubjectAccess);
        }
        {
            List<TriggerDataLost> theTriggerDataLost;
            theTriggerDataLost = this.getTriggerDataLost();
            toStringBuilder.append("triggerDataLost", theTriggerDataLost);
        }
        {
            List<TriggerOnViolation> theTriggerOnViolation;
            theTriggerOnViolation = this.getTriggerOnViolation();
            toStringBuilder.append("triggerOnViolation", theTriggerOnViolation);
        }
        {
            List<ActionDeletePersonalData> theActionDeletePersonalData;
            theActionDeletePersonalData = this.getActionDeletePersonalData();
            toStringBuilder.append("actionDeletePersonalData", theActionDeletePersonalData);
        }
        {
            List<ActionAnonymizePersonalData> theActionAnonymizePersonalData;
            theActionAnonymizePersonalData = this.getActionAnonymizePersonalData();
            toStringBuilder.append("actionAnonymizePersonalData", theActionAnonymizePersonalData);
        }
        {
            List<ActionNotifyDataSubject> theActionNotifyDataSubject;
            theActionNotifyDataSubject = this.getActionNotifyDataSubject();
            toStringBuilder.append("actionNotifyDataSubject", theActionNotifyDataSubject);
        }
        {
            List<ActionLog> theActionLog;
            theActionLog = this.getActionLog();
            toStringBuilder.append("actionLog", theActionLog);
        }
        {
            List<ActionSecureLog> theActionSecureLog;
            theActionSecureLog = this.getActionSecureLog();
            toStringBuilder.append("actionSecureLog", theActionSecureLog);
        }
        {
            String theElementId;
            theElementId = this.getElementId();
            toStringBuilder.append("elementId", theElementId);
        }
    }

    public String toString() {
        final ToStringBuilder toStringBuilder = new JAXBToStringBuilder(this);
        toString(toStringBuilder);
        return toStringBuilder.toString();
    }

}
