/*******************************************************************************
 * Copyright (c) 2013, SAP AG
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions 
 * are met:
 *  
 *     - Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *     - Redistributions in binary form must reproduce the above copyright 
 *      notice, this list of conditions and the following disclaimer in the 
 *      documentation and/or other materials provided with the distribution.
 *     - Neither the name of the SAP AG nor the names of its contributors may
 *      be used to endorse or promote products derived from this software 
 *      without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF 
 * THE POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.03 at 09:58:45 AM CET 
//


package eu.primelife.ppl.stickypolicy.obligation.impl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.primelife.ppl.stickypolicy.obligation.impl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ObligationsSet_QNAME = new QName("http://www.primelife.eu/ppl/obligation/mismatch", "ObligationsSet");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.primelife.ppl.stickypolicy.obligation.impl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Mismatches }
     * 
     */
    public Mismatches createMismatches() {
        return new Mismatches();
    }

    /**
     * Create an instance of {@link MismatchPolicy }
     * 
     */
    public MismatchPolicy createMismatchPolicy() {
        return new MismatchPolicy();
    }

    /**
     * Create an instance of {@link ObligationsSet }
     * 
     */
    public ObligationsSet createObligationsSet() {
        return new ObligationsSet();
    }

    /**
     * Create an instance of {@link Mismatch }
     * 
     */
    public Mismatch createMismatch() {
        return new Mismatch();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObligationsSet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/obligation/mismatch", name = "ObligationsSet")
    public JAXBElement<ObligationsSet> createObligationsSet(ObligationsSet value) {
        return new JAXBElement<ObligationsSet>(_ObligationsSet_QNAME, ObligationsSet.class, null, value);
    }

}
