/*******************************************************************************
 * Copyright (c) 2013, SAP AG
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions 
 * are met:
 *  
 *     - Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *     - Redistributions in binary form must reproduce the above copyright 
 *      notice, this list of conditions and the following disclaimer in the 
 *      documentation and/or other materials provided with the distribution.
 *     - Neither the name of the SAP AG nor the names of its contributors may
 *      be used to endorse or promote products derived from this software 
 *      without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF 
 * THE POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.03 at 09:58:45 AM CET 
//


package eu.primelife.ppl.stickypolicy.obligation.impl;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBToStringBuilder;


/**
 * <p>Java class for ObligationsSet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ObligationsSet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://www.primelife.eu/ppl/obligation}ObligationsSet"/>
 *         &lt;/choice>
 *         &lt;element name="Mismatches" type="{http://www.primelife.eu/ppl/obligation/mismatch}Mismatches" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="matching" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="mismatchId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObligationsSet", propOrder = {
    "obligationsSet",
    "mismatches"
})
@Entity(name = "eu.primelife.ppl.stickypolicy.obligation.impl.ObligationsSet")
@Table(name = "OBLIGATIONSSET")
@Inheritance(strategy = InheritanceType.JOINED)
public class ObligationsSet
    implements Serializable, Equals, HashCode, ToString
{

    @XmlElement(name = "ObligationsSet", namespace = "http://www.primelife.eu/ppl/obligation")
    protected eu.primelife.ppl.policy.obligation.impl.ObligationsSet obligationsSet;
    @XmlElement(name = "Mismatches")
    protected Mismatches mismatches;
    @XmlAttribute
    protected Boolean matching;
    @XmlAttribute
    protected String mismatchId;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the obligationsSet property.
     * 
     * @return
     *     possible object is
     *     {@link eu.primelife.ppl.policy.obligation.impl.ObligationsSet }
     *     
     */
    @ManyToOne(targetEntity = eu.primelife.ppl.policy.obligation.impl.ObligationsSet.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "OBLIGATIONSSET_OBLIGATIONSSE_0")
    public eu.primelife.ppl.policy.obligation.impl.ObligationsSet getObligationsSet() {
        return obligationsSet;
    }

    /**
     * Sets the value of the obligationsSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link eu.primelife.ppl.policy.obligation.impl.ObligationsSet }
     *     
     */
    public void setObligationsSet(eu.primelife.ppl.policy.obligation.impl.ObligationsSet value) {
        this.obligationsSet = value;
    }

    /**
     * Gets the value of the mismatches property.
     * 
     * @return
     *     possible object is
     *     {@link Mismatches }
     *     
     */
    @ManyToOne(targetEntity = Mismatches.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "MISMATCHES_OBLIGATIONSSET_HJ_0")
    public Mismatches getMismatches() {
        return mismatches;
    }

    /**
     * Sets the value of the mismatches property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mismatches }
     *     
     */
    public void setMismatches(Mismatches value) {
        this.mismatches = value;
    }

    /**
     * Gets the value of the matching property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    @Basic
    @Column(name = "MATCHING")
    public boolean isMatching() {
        if (matching == null) {
            return true;
        } else {
            return matching;
        }
    }

    /**
     * Sets the value of the matching property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMatching(Boolean value) {
        this.matching = value;
    }

    /**
     * Gets the value of the mismatchId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "MISMATCHID", length = 255)
    public String getMismatchId() {
        return mismatchId;
    }

    /**
     * Sets the value of the mismatchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMismatchId(String value) {
        this.mismatchId = value;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof ObligationsSet)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        final ObligationsSet that = ((ObligationsSet) object);
        equalsBuilder.append(this.getObligationsSet(), that.getObligationsSet());
        equalsBuilder.append(this.getMismatches(), that.getMismatches());
        equalsBuilder.append(this.isMatching(), that.isMatching());
        equalsBuilder.append(this.getMismatchId(), that.getMismatchId());
    }

    public boolean equals(Object object) {
        if (!(object instanceof ObligationsSet)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        hashCodeBuilder.append(this.getObligationsSet());
        hashCodeBuilder.append(this.getMismatches());
        hashCodeBuilder.append(this.isMatching());
        hashCodeBuilder.append(this.getMismatchId());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

    public void toString(ToStringBuilder toStringBuilder) {
        {
            eu.primelife.ppl.policy.obligation.impl.ObligationsSet theObligationsSet;
            theObligationsSet = this.getObligationsSet();
            toStringBuilder.append("obligationsSet", theObligationsSet);
        }
        {
            Mismatches theMismatches;
            theMismatches = this.getMismatches();
            toStringBuilder.append("mismatches", theMismatches);
        }
        {
            Boolean theMatching;
            theMatching = this.isMatching();
            toStringBuilder.append("matching", theMatching);
        }
        {
            String theMismatchId;
            theMismatchId = this.getMismatchId();
            toStringBuilder.append("mismatchId", theMismatchId);
        }
    }

    public String toString() {
        final ToStringBuilder toStringBuilder = new JAXBToStringBuilder(this);
        toString(toStringBuilder);
        return toStringBuilder.toString();
    }

}
