/*******************************************************************************
 * Copyright (c) 2013, SAP AG
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions 
 * are met:
 *  
 *     - Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *     - Redistributions in binary form must reproduce the above copyright 
 *      notice, this list of conditions and the following disclaimer in the 
 *      documentation and/or other materials provided with the distribution.
 *     - Neither the name of the SAP AG nor the names of its contributors may
 *      be used to endorse or promote products derived from this software 
 *      without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF 
 * THE POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.03 at 09:58:45 AM CET 
//


package eu.primelife.ppl.policy.obligation.impl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.primelife.ppl.policy.obligation.impl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TriggersSet_QNAME = new QName("http://www.primelife.eu/ppl/obligation", "TriggersSet");
    private final static QName _ActionNotifyDataSubject_QNAME = new QName("http://www.primelife.eu/ppl/obligation", "ActionNotifyDataSubject");
    private final static QName _TriggerDataLost_QNAME = new QName("http://www.primelife.eu/ppl/obligation", "TriggerDataLost");
    private final static QName _DateAndTime_QNAME = new QName("http://www.primelife.eu/ppl/obligation", "DateAndTime");
    private final static QName _TriggerPersonalDataAccessedForPurpose_QNAME = new QName("http://www.primelife.eu/ppl/obligation", "TriggerPersonalDataAccessedForPurpose");
    private final static QName _TriggerDataSubjectAccess_QNAME = new QName("http://www.primelife.eu/ppl/obligation", "TriggerDataSubjectAccess");
    private final static QName _TriggerAtTime_QNAME = new QName("http://www.primelife.eu/ppl/obligation", "TriggerAtTime");
    private final static QName _TriggerOnViolation_QNAME = new QName("http://www.primelife.eu/ppl/obligation", "TriggerOnViolation");
    private final static QName _Obligation_QNAME = new QName("http://www.primelife.eu/ppl/obligation", "Obligation");
    private final static QName _ActionSecureLog_QNAME = new QName("http://www.primelife.eu/ppl/obligation", "ActionSecureLog");
    private final static QName _Duration_QNAME = new QName("http://www.primelife.eu/ppl/obligation", "Duration");
    private final static QName _TriggerPeriodic_QNAME = new QName("http://www.primelife.eu/ppl/obligation", "TriggerPeriodic");
    private final static QName _Trigger_QNAME = new QName("http://www.primelife.eu/ppl/obligation", "Trigger");
    private final static QName _ActionDeletePersonalData_QNAME = new QName("http://www.primelife.eu/ppl/obligation", "ActionDeletePersonalData");
    private final static QName _ActionLog_QNAME = new QName("http://www.primelife.eu/ppl/obligation", "ActionLog");
    private final static QName _TriggerPersonalDataSent_QNAME = new QName("http://www.primelife.eu/ppl/obligation", "TriggerPersonalDataSent");
    private final static QName _Action_QNAME = new QName("http://www.primelife.eu/ppl/obligation", "Action");
    private final static QName _TriggerPersonalDataDeleted_QNAME = new QName("http://www.primelife.eu/ppl/obligation", "TriggerPersonalDataDeleted");
    private final static QName _ObligationsSet_QNAME = new QName("http://www.primelife.eu/ppl/obligation", "ObligationsSet");
    private final static QName _ActionAnonymizePersonalData_QNAME = new QName("http://www.primelife.eu/ppl/obligation", "ActionAnonymizePersonalData");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.primelife.ppl.policy.obligation.impl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TriggerDataSubjectAccess }
     * 
     */
    public TriggerDataSubjectAccess createTriggerDataSubjectAccess() {
        return new TriggerDataSubjectAccess();
    }

    /**
     * Create an instance of {@link TriggerDataLost }
     * 
     */
    public TriggerDataLost createTriggerDataLost() {
        return new TriggerDataLost();
    }

    /**
     * Create an instance of {@link ActionLog }
     * 
     */
    public ActionLog createActionLog() {
        return new ActionLog();
    }

    /**
     * Create an instance of {@link TriggerOnViolation }
     * 
     */
    public TriggerOnViolation createTriggerOnViolation() {
        return new TriggerOnViolation();
    }

    /**
     * Create an instance of {@link Obligation }
     * 
     */
    public Obligation createObligation() {
        return new Obligation();
    }

    /**
     * Create an instance of {@link Duration }
     * 
     */
    public Duration createDuration() {
        return new Duration();
    }

    /**
     * Create an instance of {@link TriggerPersonalDataAccessedForPurpose }
     * 
     */
    public TriggerPersonalDataAccessedForPurpose createTriggerPersonalDataAccessedForPurpose() {
        return new TriggerPersonalDataAccessedForPurpose();
    }

    /**
     * Create an instance of {@link DateAndTime }
     * 
     */
    public DateAndTime createDateAndTime() {
        return new DateAndTime();
    }

    /**
     * Create an instance of {@link TriggersSet }
     * 
     */
    public TriggersSet createTriggersSet() {
        return new TriggersSet();
    }

    /**
     * Create an instance of {@link Action }
     * 
     */
    public Action createAction() {
        return new Action();
    }

    /**
     * Create an instance of {@link ObligationsSet }
     * 
     */
    public ObligationsSet createObligationsSet() {
        return new ObligationsSet();
    }

    /**
     * Create an instance of {@link TriggerAtTime }
     * 
     */
    public TriggerAtTime createTriggerAtTime() {
        return new TriggerAtTime();
    }

    /**
     * Create an instance of {@link ActionAnonymizePersonalData }
     * 
     */
    public ActionAnonymizePersonalData createActionAnonymizePersonalData() {
        return new ActionAnonymizePersonalData();
    }

    /**
     * Create an instance of {@link ActionDeletePersonalData }
     * 
     */
    public ActionDeletePersonalData createActionDeletePersonalData() {
        return new ActionDeletePersonalData();
    }

    /**
     * Create an instance of {@link ActionSecureLog }
     * 
     */
    public ActionSecureLog createActionSecureLog() {
        return new ActionSecureLog();
    }

    /**
     * Create an instance of {@link TriggerPersonalDataDeleted }
     * 
     */
    public TriggerPersonalDataDeleted createTriggerPersonalDataDeleted() {
        return new TriggerPersonalDataDeleted();
    }

    /**
     * Create an instance of {@link Trigger }
     * 
     */
    public Trigger createTrigger() {
        return new Trigger();
    }

    /**
     * Create an instance of {@link ActionNotifyDataSubject }
     * 
     */
    public ActionNotifyDataSubject createActionNotifyDataSubject() {
        return new ActionNotifyDataSubject();
    }

    /**
     * Create an instance of {@link TriggerPersonalDataSent }
     * 
     */
    public TriggerPersonalDataSent createTriggerPersonalDataSent() {
        return new TriggerPersonalDataSent();
    }

    /**
     * Create an instance of {@link TriggerPeriodic }
     * 
     */
    public TriggerPeriodic createTriggerPeriodic() {
        return new TriggerPeriodic();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TriggersSet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/obligation", name = "TriggersSet")
    public JAXBElement<TriggersSet> createTriggersSet(TriggersSet value) {
        return new JAXBElement<TriggersSet>(_TriggersSet_QNAME, TriggersSet.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActionNotifyDataSubject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/obligation", name = "ActionNotifyDataSubject", substitutionHeadNamespace = "http://www.primelife.eu/ppl/obligation", substitutionHeadName = "Action")
    public JAXBElement<ActionNotifyDataSubject> createActionNotifyDataSubject(ActionNotifyDataSubject value) {
        return new JAXBElement<ActionNotifyDataSubject>(_ActionNotifyDataSubject_QNAME, ActionNotifyDataSubject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TriggerDataLost }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/obligation", name = "TriggerDataLost", substitutionHeadNamespace = "http://www.primelife.eu/ppl/obligation", substitutionHeadName = "Trigger")
    public JAXBElement<TriggerDataLost> createTriggerDataLost(TriggerDataLost value) {
        return new JAXBElement<TriggerDataLost>(_TriggerDataLost_QNAME, TriggerDataLost.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateAndTime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/obligation", name = "DateAndTime")
    public JAXBElement<DateAndTime> createDateAndTime(DateAndTime value) {
        return new JAXBElement<DateAndTime>(_DateAndTime_QNAME, DateAndTime.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TriggerPersonalDataAccessedForPurpose }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/obligation", name = "TriggerPersonalDataAccessedForPurpose", substitutionHeadNamespace = "http://www.primelife.eu/ppl/obligation", substitutionHeadName = "Trigger")
    public JAXBElement<TriggerPersonalDataAccessedForPurpose> createTriggerPersonalDataAccessedForPurpose(TriggerPersonalDataAccessedForPurpose value) {
        return new JAXBElement<TriggerPersonalDataAccessedForPurpose>(_TriggerPersonalDataAccessedForPurpose_QNAME, TriggerPersonalDataAccessedForPurpose.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TriggerDataSubjectAccess }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/obligation", name = "TriggerDataSubjectAccess", substitutionHeadNamespace = "http://www.primelife.eu/ppl/obligation", substitutionHeadName = "Trigger")
    public JAXBElement<TriggerDataSubjectAccess> createTriggerDataSubjectAccess(TriggerDataSubjectAccess value) {
        return new JAXBElement<TriggerDataSubjectAccess>(_TriggerDataSubjectAccess_QNAME, TriggerDataSubjectAccess.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TriggerAtTime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/obligation", name = "TriggerAtTime", substitutionHeadNamespace = "http://www.primelife.eu/ppl/obligation", substitutionHeadName = "Trigger")
    public JAXBElement<TriggerAtTime> createTriggerAtTime(TriggerAtTime value) {
        return new JAXBElement<TriggerAtTime>(_TriggerAtTime_QNAME, TriggerAtTime.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TriggerOnViolation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/obligation", name = "TriggerOnViolation", substitutionHeadNamespace = "http://www.primelife.eu/ppl/obligation", substitutionHeadName = "Trigger")
    public JAXBElement<TriggerOnViolation> createTriggerOnViolation(TriggerOnViolation value) {
        return new JAXBElement<TriggerOnViolation>(_TriggerOnViolation_QNAME, TriggerOnViolation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Obligation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/obligation", name = "Obligation")
    public JAXBElement<Obligation> createObligation(Obligation value) {
        return new JAXBElement<Obligation>(_Obligation_QNAME, Obligation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActionSecureLog }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/obligation", name = "ActionSecureLog", substitutionHeadNamespace = "http://www.primelife.eu/ppl/obligation", substitutionHeadName = "Action")
    public JAXBElement<ActionSecureLog> createActionSecureLog(ActionSecureLog value) {
        return new JAXBElement<ActionSecureLog>(_ActionSecureLog_QNAME, ActionSecureLog.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Duration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/obligation", name = "Duration")
    public JAXBElement<Duration> createDuration(Duration value) {
        return new JAXBElement<Duration>(_Duration_QNAME, Duration.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TriggerPeriodic }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/obligation", name = "TriggerPeriodic", substitutionHeadNamespace = "http://www.primelife.eu/ppl/obligation", substitutionHeadName = "Trigger")
    public JAXBElement<TriggerPeriodic> createTriggerPeriodic(TriggerPeriodic value) {
        return new JAXBElement<TriggerPeriodic>(_TriggerPeriodic_QNAME, TriggerPeriodic.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Trigger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/obligation", name = "Trigger")
    public JAXBElement<Trigger> createTrigger(Trigger value) {
        return new JAXBElement<Trigger>(_Trigger_QNAME, Trigger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActionDeletePersonalData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/obligation", name = "ActionDeletePersonalData", substitutionHeadNamespace = "http://www.primelife.eu/ppl/obligation", substitutionHeadName = "Action")
    public JAXBElement<ActionDeletePersonalData> createActionDeletePersonalData(ActionDeletePersonalData value) {
        return new JAXBElement<ActionDeletePersonalData>(_ActionDeletePersonalData_QNAME, ActionDeletePersonalData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActionLog }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/obligation", name = "ActionLog", substitutionHeadNamespace = "http://www.primelife.eu/ppl/obligation", substitutionHeadName = "Action")
    public JAXBElement<ActionLog> createActionLog(ActionLog value) {
        return new JAXBElement<ActionLog>(_ActionLog_QNAME, ActionLog.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TriggerPersonalDataSent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/obligation", name = "TriggerPersonalDataSent", substitutionHeadNamespace = "http://www.primelife.eu/ppl/obligation", substitutionHeadName = "Trigger")
    public JAXBElement<TriggerPersonalDataSent> createTriggerPersonalDataSent(TriggerPersonalDataSent value) {
        return new JAXBElement<TriggerPersonalDataSent>(_TriggerPersonalDataSent_QNAME, TriggerPersonalDataSent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Action }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/obligation", name = "Action")
    public JAXBElement<Action> createAction(Action value) {
        return new JAXBElement<Action>(_Action_QNAME, Action.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TriggerPersonalDataDeleted }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/obligation", name = "TriggerPersonalDataDeleted", substitutionHeadNamespace = "http://www.primelife.eu/ppl/obligation", substitutionHeadName = "Trigger")
    public JAXBElement<TriggerPersonalDataDeleted> createTriggerPersonalDataDeleted(TriggerPersonalDataDeleted value) {
        return new JAXBElement<TriggerPersonalDataDeleted>(_TriggerPersonalDataDeleted_QNAME, TriggerPersonalDataDeleted.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObligationsSet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/obligation", name = "ObligationsSet")
    public JAXBElement<ObligationsSet> createObligationsSet(ObligationsSet value) {
        return new JAXBElement<ObligationsSet>(_ObligationsSet_QNAME, ObligationsSet.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActionAnonymizePersonalData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.primelife.eu/ppl/obligation", name = "ActionAnonymizePersonalData", substitutionHeadNamespace = "http://www.primelife.eu/ppl/obligation", substitutionHeadName = "Action")
    public JAXBElement<ActionAnonymizePersonalData> createActionAnonymizePersonalData(ActionAnonymizePersonalData value) {
        return new JAXBElement<ActionAnonymizePersonalData>(_ActionAnonymizePersonalData_QNAME, ActionAnonymizePersonalData.class, null, value);
    }

}
