/*******************************************************************************
 * Copyright (c) 2013, SAP AG
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions 
 * are met:
 *  
 *     - Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *     - Redistributions in binary form must reproduce the above copyright 
 *      notice, this list of conditions and the following disclaimer in the 
 *      documentation and/or other materials provided with the distribution.
 *     - Neither the name of the SAP AG nor the names of its contributors may
 *      be used to endorse or promote products derived from this software 
 *      without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF 
 * THE POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.03 at 09:58:45 AM CET 
//


package eu.primelife.ppl.policy.obligation.impl;

import java.io.Serializable;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBToStringBuilder;


/**
 * <p>Java class for TriggerPeriodic complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TriggerPeriodic">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.primelife.eu/ppl/obligation}Trigger">
 *       &lt;sequence>
 *         &lt;element name="Start" type="{http://www.primelife.eu/ppl/obligation}DateAndTime"/>
 *         &lt;element name="End" type="{http://www.primelife.eu/ppl/obligation}DateAndTime"/>
 *         &lt;element name="MaxDelay" type="{http://www.primelife.eu/ppl/obligation}Duration"/>
 *         &lt;element name="Period" type="{http://www.primelife.eu/ppl/obligation}Duration"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TriggerPeriodic", propOrder = {
    "start",
    "end",
    "maxDelay",
    "period"
})
@Entity(name = "eu.primelife.ppl.policy.obligation.impl.TriggerPeriodic")
@Table(name = "TRIGGERPERIODIC")
public class TriggerPeriodic
    extends Trigger
    implements Serializable, Equals, HashCode, ToString
{

    @XmlElement(name = "Start", required = true)
    protected DateAndTime start;
    @XmlElement(name = "End", required = true)
    protected DateAndTime end;
    @XmlElement(name = "MaxDelay", required = true)
    protected Duration maxDelay;
    @XmlElement(name = "Period", required = true)
    protected Duration period;

    /**
     * Gets the value of the start property.
     * 
     * @return
     *     possible object is
     *     {@link DateAndTime }
     *     
     */
    @ManyToOne(targetEntity = DateAndTime.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "START__TRIGGERPERIODIC_HJID")
    public DateAndTime getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAndTime }
     *     
     */
    public void setStart(DateAndTime value) {
        this.start = value;
    }

    /**
     * Gets the value of the end property.
     * 
     * @return
     *     possible object is
     *     {@link DateAndTime }
     *     
     */
    @ManyToOne(targetEntity = DateAndTime.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "END__TRIGGERPERIODIC_HJID")
    public DateAndTime getEnd() {
        return end;
    }

    /**
     * Sets the value of the end property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateAndTime }
     *     
     */
    public void setEnd(DateAndTime value) {
        this.end = value;
    }

    /**
     * Gets the value of the maxDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    @ManyToOne(targetEntity = Duration.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "MAXDELAY_TRIGGERPERIODIC_HJID")
    public Duration getMaxDelay() {
        return maxDelay;
    }

    /**
     * Sets the value of the maxDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setMaxDelay(Duration value) {
        this.maxDelay = value;
    }

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    @ManyToOne(targetEntity = Duration.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "PERIOD_TRIGGERPERIODIC_HJID")
    public Duration getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setPeriod(Duration value) {
        this.period = value;
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof TriggerPeriodic)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        super.equals(object, equalsBuilder);
        final TriggerPeriodic that = ((TriggerPeriodic) object);
        equalsBuilder.append(this.getStart(), that.getStart());
        equalsBuilder.append(this.getEnd(), that.getEnd());
        equalsBuilder.append(this.getMaxDelay(), that.getMaxDelay());
        equalsBuilder.append(this.getPeriod(), that.getPeriod());
    }

    public boolean equals(Object object) {
        if (!(object instanceof TriggerPeriodic)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        super.hashCode(hashCodeBuilder);
        hashCodeBuilder.append(this.getStart());
        hashCodeBuilder.append(this.getEnd());
        hashCodeBuilder.append(this.getMaxDelay());
        hashCodeBuilder.append(this.getPeriod());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

    public void toString(ToStringBuilder toStringBuilder) {
        super.toString(toStringBuilder);
        {
            DateAndTime theStart;
            theStart = this.getStart();
            toStringBuilder.append("start", theStart);
        }
        {
            DateAndTime theEnd;
            theEnd = this.getEnd();
            toStringBuilder.append("end", theEnd);
        }
        {
            Duration theMaxDelay;
            theMaxDelay = this.getMaxDelay();
            toStringBuilder.append("maxDelay", theMaxDelay);
        }
        {
            Duration thePeriod;
            thePeriod = this.getPeriod();
            toStringBuilder.append("period", thePeriod);
        }
    }

    public String toString() {
        final ToStringBuilder toStringBuilder = new JAXBToStringBuilder(this);
        toString(toStringBuilder);
        return toStringBuilder.toString();
    }

}
