/*******************************************************************************
 * Copyright (c) 2013, SAP AG
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions 
 * are met:
 *  
 *     - Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *     - Redistributions in binary form must reproduce the above copyright 
 *      notice, this list of conditions and the following disclaimer in the 
 *      documentation and/or other materials provided with the distribution.
 *     - Neither the name of the SAP AG nor the names of its contributors may
 *      be used to endorse or promote products derived from this software 
 *      without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF 
 * THE POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.03 at 09:58:45 AM CET 
//


package org.w3._2001._04.xmlenc_;

import java.io.Serializable;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.namespace.QName;
import org.jvnet.hyperjaxb3.item.Item;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XmlAdapterUtils;

@XmlAccessorType(XmlAccessType.FIELD)
@Entity(name = "org.w3._2001._04.xmlenc_.ReferenceListDataReferenceOrKeyReferenceItem")
@Table(name = "REFERENCELISTDATAREFERENCEOR_0")
@Inheritance(strategy = InheritanceType.JOINED)
public class ReferenceListDataReferenceOrKeyReferenceItem
    implements Serializable, Item<JAXBElement<ReferenceType>>
{

    @XmlElementRefs({
        @XmlElementRef(name = "DataReference", namespace = "http://www.w3.org/2001/04/xmlenc#", type = JAXBElement.class),
        @XmlElementRef(name = "KeyReference", namespace = "http://www.w3.org/2001/04/xmlenc#", type = JAXBElement.class)
    })
    protected JAXBElement<ReferenceType> item;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * 
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     *     
     */
    @Transient
    public JAXBElement<ReferenceType> getItem() {
        return item;
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     *     
     */
    public void setItem(JAXBElement<ReferenceType> value) {
        this.item = ((JAXBElement<ReferenceType> ) value);
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    @ManyToOne(targetEntity = ReferenceType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ITEMDATAREFERENCE_REFERENCEL_0")
    public ReferenceType getItemDataReference() {
        if (XmlAdapterUtils.isJAXBElement(ReferenceType.class, new QName("http://www.w3.org/2001/04/xmlenc#", "DataReference"), ReferenceList.class, this.getItem())) {
            return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends ReferenceType> ) this.getItem()));
        } else {
            return null;
        }
    }

    public void setItemDataReference(ReferenceType target) {
        if (target!= null) {
            setItem(XmlAdapterUtils.marshallJAXBElement(ReferenceType.class, new QName("http://www.w3.org/2001/04/xmlenc#", "DataReference"), ReferenceList.class, target));
        }
    }

    @ManyToOne(targetEntity = ReferenceType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ITEMKEYREFERENCE_REFERENCELI_0")
    public ReferenceType getItemKeyReference() {
        if (XmlAdapterUtils.isJAXBElement(ReferenceType.class, new QName("http://www.w3.org/2001/04/xmlenc#", "KeyReference"), ReferenceList.class, this.getItem())) {
            return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends ReferenceType> ) this.getItem()));
        } else {
            return null;
        }
    }

    public void setItemKeyReference(ReferenceType target) {
        if (target!= null) {
            setItem(XmlAdapterUtils.marshallJAXBElement(ReferenceType.class, new QName("http://www.w3.org/2001/04/xmlenc#", "KeyReference"), ReferenceList.class, target));
        }
    }

}
