/*******************************************************************************
 * Copyright (c) 2013, SAP AG
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions 
 * are met:
 *  
 *     - Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *     - Redistributions in binary form must reproduce the above copyright 
 *      notice, this list of conditions and the following disclaimer in the 
 *      documentation and/or other materials provided with the distribution.
 *     - Neither the name of the SAP AG nor the names of its contributors may
 *      be used to endorse or promote products derived from this software 
 *      without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF 
 * THE POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.03 at 09:58:45 AM CET 
//


package oasis.names.tc.saml._2_0.assertion;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.namespace.QName;
import org.jvnet.hyperjaxb3.item.Item;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XmlAdapterUtils;

@XmlAccessorType(XmlAccessType.FIELD)
@Entity(name = "oasis.names.tc.saml._2_0.assertion.AuthnContextTypeContentItem")
@Table(name = "AUTHNCONTEXTTYPECONTENTITEM")
@Inheritance(strategy = InheritanceType.JOINED)
public class AuthnContextTypeContentItem
    implements Serializable, Item<JAXBElement<?>>
{

    @XmlElementRefs({
        @XmlElementRef(name = "AuthnContextDecl", namespace = "urn:oasis:names:tc:SAML:2.0:assertion", type = JAXBElement.class),
        @XmlElementRef(name = "AuthnContextClassRef", namespace = "urn:oasis:names:tc:SAML:2.0:assertion", type = JAXBElement.class),
        @XmlElementRef(name = "AuthenticatingAuthority", namespace = "urn:oasis:names:tc:SAML:2.0:assertion", type = JAXBElement.class),
        @XmlElementRef(name = "AuthnContextDeclRef", namespace = "urn:oasis:names:tc:SAML:2.0:assertion", type = JAXBElement.class)
    })
    protected JAXBElement<?> item;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * 
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    @Transient
    public JAXBElement<?> getItem() {
        return item;
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setItem(JAXBElement<?> value) {
        this.item = ((JAXBElement<?> ) value);
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    @Transient
    public Object getItemAuthnContextDecl() {
        if (XmlAdapterUtils.isJAXBElement(Object.class, new QName("urn:oasis:names:tc:SAML:2.0:assertion", "AuthnContextDecl"), JAXBElement.GlobalScope.class, this.getItem())) {
            return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<?> ) this.getItem()));
        } else {
            return null;
        }
    }

    public void setItemAuthnContextDecl(Object target) {
        if (target!= null) {
            setItem(XmlAdapterUtils.marshallJAXBElement(Object.class, new QName("urn:oasis:names:tc:SAML:2.0:assertion", "AuthnContextDecl"), JAXBElement.GlobalScope.class, target));
        }
    }

    @SuppressWarnings("unchecked")
    @Basic
    @Column(name = "ITEMAUTHNCONTEXTCLASSREF")
    public String getItemAuthnContextClassRef() {
        if (XmlAdapterUtils.isJAXBElement(String.class, new QName("urn:oasis:names:tc:SAML:2.0:assertion", "AuthnContextClassRef"), JAXBElement.GlobalScope.class, this.getItem())) {
            return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends String> ) this.getItem()));
        } else {
            return null;
        }
    }

    public void setItemAuthnContextClassRef(String target) {
        if (target!= null) {
            setItem(XmlAdapterUtils.marshallJAXBElement(String.class, new QName("urn:oasis:names:tc:SAML:2.0:assertion", "AuthnContextClassRef"), JAXBElement.GlobalScope.class, target));
        }
    }

    @SuppressWarnings("unchecked")
    @Basic
    @Column(name = "ITEMAUTHENTICATINGAUTHORITY")
    public String getItemAuthenticatingAuthority() {
        if (XmlAdapterUtils.isJAXBElement(String.class, new QName("urn:oasis:names:tc:SAML:2.0:assertion", "AuthenticatingAuthority"), JAXBElement.GlobalScope.class, this.getItem())) {
            return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends String> ) this.getItem()));
        } else {
            return null;
        }
    }

    public void setItemAuthenticatingAuthority(String target) {
        if (target!= null) {
            setItem(XmlAdapterUtils.marshallJAXBElement(String.class, new QName("urn:oasis:names:tc:SAML:2.0:assertion", "AuthenticatingAuthority"), JAXBElement.GlobalScope.class, target));
        }
    }

    @SuppressWarnings("unchecked")
    @Basic
    @Column(name = "ITEMAUTHNCONTEXTDECLREF")
    public String getItemAuthnContextDeclRef() {
        if (XmlAdapterUtils.isJAXBElement(String.class, new QName("urn:oasis:names:tc:SAML:2.0:assertion", "AuthnContextDeclRef"), JAXBElement.GlobalScope.class, this.getItem())) {
            return XmlAdapterUtils.unmarshallJAXBElement(((JAXBElement<? extends String> ) this.getItem()));
        } else {
            return null;
        }
    }

    public void setItemAuthnContextDeclRef(String target) {
        if (target!= null) {
            setItem(XmlAdapterUtils.marshallJAXBElement(String.class, new QName("urn:oasis:names:tc:SAML:2.0:assertion", "AuthnContextDeclRef"), JAXBElement.GlobalScope.class, target));
        }
    }

}
