/*******************************************************************************
 * Copyright (c) 2013, SAP AG
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions 
 * are met:
 *  
 *     - Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *     - Redistributions in binary form must reproduce the above copyright 
 *      notice, this list of conditions and the following disclaimer in the 
 *      documentation and/or other materials provided with the distribution.
 *     - Neither the name of the SAP AG nor the names of its contributors may
 *      be used to endorse or promote products derived from this software 
 *      without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF 
 * THE POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.03 at 09:58:45 AM CET 
//


package eu.primelife.ppl.stickypolicy.impl;

import java.io.Serializable;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import eu.primelife.ppl.stickypolicy.authorization.impl.AuthorizationsMismatchType;
import eu.primelife.ppl.stickypolicy.obligation.impl.Mismatches;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBToStringBuilder;


/**
 * <p>Java class for MismatchesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MismatchesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.primelife.eu/ppl/authorization/mismatch}AuthorizationsMismatch" minOccurs="0"/>
 *         &lt;element name="ObligationsMismatch" type="{http://www.primelife.eu/ppl/obligation/mismatch}Mismatches" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MismatchesType", propOrder = {
    "authorizationsMismatch",
    "obligationsMismatch"
})
@Entity(name = "eu.primelife.ppl.stickypolicy.impl.MismatchesType")
@Table(name = "MISMATCHESTYPE")
@Inheritance(strategy = InheritanceType.JOINED)
public class MismatchesType
    implements Serializable, Equals, HashCode, ToString
{

    @XmlElement(name = "AuthorizationsMismatch", namespace = "http://www.primelife.eu/ppl/authorization/mismatch")
    protected AuthorizationsMismatchType authorizationsMismatch;
    @XmlElement(name = "ObligationsMismatch")
    protected Mismatches obligationsMismatch;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the authorizationsMismatch property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorizationsMismatchType }
     *     
     */
    @ManyToOne(targetEntity = AuthorizationsMismatchType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "AUTHORIZATIONSMISMATCH_MISMA_0")
    public AuthorizationsMismatchType getAuthorizationsMismatch() {
        return authorizationsMismatch;
    }

    /**
     * Sets the value of the authorizationsMismatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorizationsMismatchType }
     *     
     */
    public void setAuthorizationsMismatch(AuthorizationsMismatchType value) {
        this.authorizationsMismatch = value;
    }

    /**
     * Gets the value of the obligationsMismatch property.
     * 
     * @return
     *     possible object is
     *     {@link Mismatches }
     *     
     */
    @ManyToOne(targetEntity = Mismatches.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "OBLIGATIONSMISMATCH_MISMATCH_0")
    public Mismatches getObligationsMismatch() {
        return obligationsMismatch;
    }

    /**
     * Sets the value of the obligationsMismatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mismatches }
     *     
     */
    public void setObligationsMismatch(Mismatches value) {
        this.obligationsMismatch = value;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof MismatchesType)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        final MismatchesType that = ((MismatchesType) object);
        equalsBuilder.append(this.getAuthorizationsMismatch(), that.getAuthorizationsMismatch());
        equalsBuilder.append(this.getObligationsMismatch(), that.getObligationsMismatch());
    }

    public boolean equals(Object object) {
        if (!(object instanceof MismatchesType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        hashCodeBuilder.append(this.getAuthorizationsMismatch());
        hashCodeBuilder.append(this.getObligationsMismatch());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

    public void toString(ToStringBuilder toStringBuilder) {
        {
            AuthorizationsMismatchType theAuthorizationsMismatch;
            theAuthorizationsMismatch = this.getAuthorizationsMismatch();
            toStringBuilder.append("authorizationsMismatch", theAuthorizationsMismatch);
        }
        {
            Mismatches theObligationsMismatch;
            theObligationsMismatch = this.getObligationsMismatch();
            toStringBuilder.append("obligationsMismatch", theObligationsMismatch);
        }
    }

    public String toString() {
        final ToStringBuilder toStringBuilder = new JAXBToStringBuilder(this);
        toString(toStringBuilder);
        return toStringBuilder.toString();
    }

}
