/*******************************************************************************
 * Copyright (c) 2013, SAP AG
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions 
 * are met:
 *  
 *     - Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *     - Redistributions in binary form must reproduce the above copyright 
 *      notice, this list of conditions and the following disclaimer in the 
 *      documentation and/or other materials provided with the distribution.
 *     - Neither the name of the SAP AG nor the names of its contributors may
 *      be used to endorse or promote products derived from this software 
 *      without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF 
 * THE POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.03 at 09:58:45 AM CET 
//


package eu.primelife.ppl.claims.impl;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import eu.primelife.ppl.policy.impl.PolicySetType;
import eu.primelife.ppl.policy.impl.PolicyType;
import oasis.names.tc.saml._2_0.assertion.StatementAbstractType;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.jvnet.hyperjaxb3.item.ItemUtils;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBToStringBuilder;


/**
 * <p>Java class for PPLPolicyStatementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PPLPolicyStatementType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:oasis:names:tc:SAML:2.0:assertion}StatementAbstractType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://www.primelife.eu/ppl}Policy"/>
 *         &lt;element ref="{http://www.primelife.eu/ppl}PolicySet"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PPLPolicyStatementType", propOrder = {
    "policyOrPolicySet"
})
@Entity(name = "eu.primelife.ppl.claims.impl.PPLPolicyStatementType")
@Table(name = "PPLPOLICYSTATEMENTTYPE")
public class PPLPolicyStatementType
    extends StatementAbstractType
    implements Serializable, Equals, HashCode, ToString
{

    @XmlElements({
        @XmlElement(name = "PolicySet", namespace = "http://www.primelife.eu/ppl", type = PolicySetType.class),
        @XmlElement(name = "Policy", namespace = "http://www.primelife.eu/ppl", type = PolicyType.class)
    })
    protected List<Object> policyOrPolicySet;
    protected transient List<PPLPolicyStatementTypePolicyOrPolicySetItem> policyOrPolicySetItems;

    /**
     * Gets the value of the policyOrPolicySet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the policyOrPolicySet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPolicyOrPolicySet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PolicySetType }
     * {@link PolicyType }
     * 
     * 
     */
    @Transient
    public List<Object> getPolicyOrPolicySet() {
        if (policyOrPolicySet == null) {
            policyOrPolicySet = new ArrayList<Object>();
        }
        return this.policyOrPolicySet;
    }

    /**
     * 
     * 
     */
    public void setPolicyOrPolicySet(List<Object> policyOrPolicySet) {
        this.policyOrPolicySet = policyOrPolicySet;
    }

    @OneToMany(targetEntity = PPLPolicyStatementTypePolicyOrPolicySetItem.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "POLICYORPOLICYSETITEMS_PPLPO_0")
    public List<PPLPolicyStatementTypePolicyOrPolicySetItem> getPolicyOrPolicySetItems() {
        if (this.policyOrPolicySetItems == null) {
            this.policyOrPolicySetItems = new ArrayList<PPLPolicyStatementTypePolicyOrPolicySetItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.policyOrPolicySet)) {
            this.policyOrPolicySet = ItemUtils.wrap(this.policyOrPolicySet, this.policyOrPolicySetItems, PPLPolicyStatementTypePolicyOrPolicySetItem.class);
        }
        return this.policyOrPolicySetItems;
    }

    public void setPolicyOrPolicySetItems(List<PPLPolicyStatementTypePolicyOrPolicySetItem> value) {
        this.policyOrPolicySet = null;
        this.policyOrPolicySetItems = null;
        this.policyOrPolicySetItems = value;
        if (this.policyOrPolicySetItems == null) {
            this.policyOrPolicySetItems = new ArrayList<PPLPolicyStatementTypePolicyOrPolicySetItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.policyOrPolicySet)) {
            this.policyOrPolicySet = ItemUtils.wrap(this.policyOrPolicySet, this.policyOrPolicySetItems, PPLPolicyStatementTypePolicyOrPolicySetItem.class);
        }
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof PPLPolicyStatementType)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        super.equals(object, equalsBuilder);
        final PPLPolicyStatementType that = ((PPLPolicyStatementType) object);
        equalsBuilder.append(this.getPolicyOrPolicySet(), that.getPolicyOrPolicySet());
    }

    public boolean equals(Object object) {
        if (!(object instanceof PPLPolicyStatementType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        super.hashCode(hashCodeBuilder);
        hashCodeBuilder.append(this.getPolicyOrPolicySet());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

    public void toString(ToStringBuilder toStringBuilder) {
        super.toString(toStringBuilder);
        {
            List<Object> thePolicyOrPolicySet;
            thePolicyOrPolicySet = this.getPolicyOrPolicySet();
            toStringBuilder.append("policyOrPolicySet", thePolicyOrPolicySet);
        }
    }

    public String toString() {
        final ToStringBuilder toStringBuilder = new JAXBToStringBuilder(this);
        toString(toStringBuilder);
        return toStringBuilder.toString();
    }

}
