/*******************************************************************************
 * Copyright (c) 2013, SAP AG
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions 
 * are met:
 *  
 *     - Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *     - Redistributions in binary form must reproduce the above copyright 
 *      notice, this list of conditions and the following disclaimer in the 
 *      documentation and/or other materials provided with the distribution.
 *     - Neither the name of the SAP AG nor the names of its contributors may
 *      be used to endorse or promote products derived from this software 
 *      without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF 
 * THE POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.03 at 09:58:45 AM CET 
//


package eu.primelife.ppl.claims.impl;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import oasis.names.tc.saml._2_0.assertion.StatementAbstractType;
import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;
import org.apache.commons.lang.builder.ToStringBuilder;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.builder.JAXBEqualsBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBHashCodeBuilder;
import org.jvnet.jaxb2_commons.lang.builder.JAXBToStringBuilder;


/**
 * <p>Java class for ResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:oasis:names:tc:SAML:2.0:assertion}StatementAbstractType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.primelife.eu/ppl/claims}MissingPII" minOccurs="0"/>
 *         &lt;element ref="{http://www.primelife.eu/ppl/claims}AccessPII" minOccurs="0"/>
 *         &lt;element ref="{http://www.primelife.eu/ppl/claims}DeneyPII" minOccurs="0"/>
 *         &lt;element ref="{http://www.primelife.eu/ppl/claims}MissingCredential" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Decision" use="required" type="{http://www.primelife.eu/ppl/claims}Decision" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponseType", propOrder = {
    "missingPII",
    "accessPII",
    "deneyPII",
    "missingCredential"
})
@Entity(name = "eu.primelife.ppl.claims.impl.ResponseType")
@Table(name = "RESPONSETYPE_0")
public class ResponseType
    extends StatementAbstractType
    implements Serializable, Equals, HashCode, ToString
{

    @XmlElement(name = "MissingPII")
    protected ListPIIType missingPII;
    @XmlElement(name = "AccessPII")
    protected ListPIIType accessPII;
    @XmlElement(name = "DeneyPII")
    protected ListPIIType deneyPII;
    @XmlElement(name = "MissingCredential")
    protected ListPIIType missingCredential;
    @XmlAttribute(name = "Decision", required = true)
    protected Decision decision;

    /**
     * Gets the value of the missingPII property.
     * 
     * @return
     *     possible object is
     *     {@link ListPIIType }
     *     
     */
    @ManyToOne(targetEntity = ListPIIType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "MISSINGPII_RESPONSETYPE_0_HJ_0")
    public ListPIIType getMissingPII() {
        return missingPII;
    }

    /**
     * Sets the value of the missingPII property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListPIIType }
     *     
     */
    public void setMissingPII(ListPIIType value) {
        this.missingPII = value;
    }

    /**
     * Gets the value of the accessPII property.
     * 
     * @return
     *     possible object is
     *     {@link ListPIIType }
     *     
     */
    @ManyToOne(targetEntity = ListPIIType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ACCESSPII_RESPONSETYPE_0_HJID")
    public ListPIIType getAccessPII() {
        return accessPII;
    }

    /**
     * Sets the value of the accessPII property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListPIIType }
     *     
     */
    public void setAccessPII(ListPIIType value) {
        this.accessPII = value;
    }

    /**
     * Gets the value of the deneyPII property.
     * 
     * @return
     *     possible object is
     *     {@link ListPIIType }
     *     
     */
    @ManyToOne(targetEntity = ListPIIType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "DENEYPII_RESPONSETYPE_0_HJID")
    public ListPIIType getDeneyPII() {
        return deneyPII;
    }

    /**
     * Sets the value of the deneyPII property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListPIIType }
     *     
     */
    public void setDeneyPII(ListPIIType value) {
        this.deneyPII = value;
    }

    /**
     * Gets the value of the missingCredential property.
     * 
     * @return
     *     possible object is
     *     {@link ListPIIType }
     *     
     */
    @ManyToOne(targetEntity = ListPIIType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "MISSINGCREDENTIAL_RESPONSETY_0")
    public ListPIIType getMissingCredential() {
        return missingCredential;
    }

    /**
     * Sets the value of the missingCredential property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListPIIType }
     *     
     */
    public void setMissingCredential(ListPIIType value) {
        this.missingCredential = value;
    }

    /**
     * Gets the value of the decision property.
     * 
     * @return
     *     possible object is
     *     {@link Decision }
     *     
     */
    @Basic
    @Column(name = "DECISION", length = 255)
    @Enumerated(EnumType.STRING)
    public Decision getDecision() {
        return decision;
    }

    /**
     * Sets the value of the decision property.
     * 
     * @param value
     *     allowed object is
     *     {@link Decision }
     *     
     */
    public void setDecision(Decision value) {
        this.decision = value;
    }

    public void equals(Object object, EqualsBuilder equalsBuilder) {
        if (!(object instanceof ResponseType)) {
            equalsBuilder.appendSuper(false);
            return ;
        }
        if (this == object) {
            return ;
        }
        super.equals(object, equalsBuilder);
        final ResponseType that = ((ResponseType) object);
        equalsBuilder.append(this.getMissingPII(), that.getMissingPII());
        equalsBuilder.append(this.getAccessPII(), that.getAccessPII());
        equalsBuilder.append(this.getDeneyPII(), that.getDeneyPII());
        equalsBuilder.append(this.getMissingCredential(), that.getMissingCredential());
        equalsBuilder.append(this.getDecision(), that.getDecision());
    }

    public boolean equals(Object object) {
        if (!(object instanceof ResponseType)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final EqualsBuilder equalsBuilder = new JAXBEqualsBuilder();
        equals(object, equalsBuilder);
        return equalsBuilder.isEquals();
    }

    public void hashCode(HashCodeBuilder hashCodeBuilder) {
        super.hashCode(hashCodeBuilder);
        hashCodeBuilder.append(this.getMissingPII());
        hashCodeBuilder.append(this.getAccessPII());
        hashCodeBuilder.append(this.getDeneyPII());
        hashCodeBuilder.append(this.getMissingCredential());
        hashCodeBuilder.append(this.getDecision());
    }

    public int hashCode() {
        final HashCodeBuilder hashCodeBuilder = new JAXBHashCodeBuilder();
        hashCode(hashCodeBuilder);
        return hashCodeBuilder.toHashCode();
    }

    public void toString(ToStringBuilder toStringBuilder) {
        super.toString(toStringBuilder);
        {
            ListPIIType theMissingPII;
            theMissingPII = this.getMissingPII();
            toStringBuilder.append("missingPII", theMissingPII);
        }
        {
            ListPIIType theAccessPII;
            theAccessPII = this.getAccessPII();
            toStringBuilder.append("accessPII", theAccessPII);
        }
        {
            ListPIIType theDeneyPII;
            theDeneyPII = this.getDeneyPII();
            toStringBuilder.append("deneyPII", theDeneyPII);
        }
        {
            ListPIIType theMissingCredential;
            theMissingCredential = this.getMissingCredential();
            toStringBuilder.append("missingCredential", theMissingCredential);
        }
        {
            Decision theDecision;
            theDecision = this.getDecision();
            toStringBuilder.append("decision", theDecision);
        }
    }

    public String toString() {
        final ToStringBuilder toStringBuilder = new JAXBToStringBuilder(this);
        toString(toStringBuilder);
        return toStringBuilder.toString();
    }

}
